export type Course = {
  title: string;
  desc: string;
  price: string;
  rating: number;
  reviews: number;
  img: string;
  badge?: string;
  type: "Cours" | "Parcours";
  href: string;
  category: string;
};

export const allCourses: Course[] = [
  // IA & Transformation digitale
  {
    title: "L'IA pour les Managers Commerciaux 5.0 : Le Cours Complet",
    desc: "Comment les managers commerciaux innovants utilisent la DATA, l'IA et la Technologie pour avoir plusieurs coups d'avance.",
    price: "$99",
    rating: 4.7,
    reviews: 1468,
    img: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/ia-pour-les-sales-managers-le-cours-complet",
    category: "transformation-digitale-4-0",
  },
  {
    title: "IA pour Assistants & Professionnels : Le Cours Complet",
    desc: "Boostez votre carrière avec l'IA. Automatisation des tâches répétitives, création de contenu optimisée, productivité x3.",
    price: "$57",
    rating: 4.7,
    reviews: 2024,
    img: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/L-IA-pour-les-professionnels",
    category: "transformation-digitale-4-0",
  },
  {
    title: "IA pour Manager RH 5.0 : Le Cours Complet",
    desc: "Comprendre l'IA de A-Z avec une bonne immersion dans les utilisations pratiques pour booster la productivité.",
    price: "$99",
    rating: 4.6,
    reviews: 336,
    img: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/L-IA-pour-les-RH",
    category: "transformation-digitale-4-0",
  },
  {
    title: "L'IA pour les DG et les Dirigeants 5.0 : Le Cours Complet",
    desc: "Comment les DG et dirigeants 5.0 utilisent la DATA, l'IA et la Technologie pour optimiser le cadrage stratégique.",
    price: "$179",
    rating: 4.8,
    reviews: 92,
    img: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?auto=format&fit=crop&w=400&q=80",
    badge: "Top noté",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/L-IA-pour-DG",
    category: "transformation-digitale-4-0",
  },
  {
    title: "Intelligence Artificielle pour les Managers",
    desc: "Comprendre l'IA de A-Z avec une immersion dans les utilisations pratiques pour booster la productivité d'un manager.",
    price: "$99",
    rating: 4.7,
    reviews: 403,
    img: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/intelligence-artificielle-pour-les-managers",
    category: "transformation-digitale-4-0",
  },

  // Dirigeant
  {
    title: "Parcours Dirigeant Certifié (PDC)",
    desc: "Acquérez les compétences clés pour briller en tant que dirigeant et réussir votre promotion.",
    price: "$519",
    rating: 4.8,
    reviews: 2724,
    img: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Parcours",
    href: "https://www.managersity.co/bundles/parcours-dirigeant-certifie-pdc",
    category: "dirigeant",
  },
  {
    title: "Le Game de la Stratégie & Disruption Marché",
    desc: "Tout ce que vous avez besoin de savoir pour affiner votre profondeur stratégique et disrupter vos marchés.",
    price: "$97",
    rating: 4.7,
    reviews: 512,
    img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=400&q=80",
    badge: "Premium",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/le-game-de-la-strategie-et-disruption-marche",
    category: "dirigeant",
  },
  {
    title: "Choix Complexes & Mécanismes Décisionnels",
    desc: "Modèles décisionnels pour identifier les signaux critiques, se poser les bonnes questions et prendre des décisions complexes.",
    price: "$59",
    rating: 4.6,
    reviews: 278,
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/choix-complexes-et-mecanismes-decisionnels",
    category: "dirigeant",
  },
  {
    title: "Leadership Situationnel & Intelligence Émotionnelle pour les Dirigeants",
    desc: "Comment les grands leaders abordent les situations complexes avec hauteur, intelligence émotionnelle.",
    price: "$59",
    rating: 4.8,
    reviews: 389,
    img: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=400&q=80",
    badge: "Top noté",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/leadership-situationnel-et-intelligence-emotionnelle-pour-les-dirigeants",
    category: "dirigeant",
  },
  {
    title: "Maturité Managériale & Enjeux de Direction Générale",
    desc: "Pour les membres de CODIR qui doivent démontrer de l'excellence Top Executive.",
    price: "$97",
    rating: 4.7,
    reviews: 893,
    img: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/maturite-manageriale-et-enjeux-de-direction-generale",
    category: "dirigeant",
  },
  {
    title: "Gestion des Parties Prenantes & Networking Diplomatique pour les Dirigeants",
    desc: "Lorsqu'un dirigeant échoue, c'est parce qu'il a échoué dans ses relations avec ses parties prenantes.",
    price: "$97",
    rating: 4.5,
    reviews: 432,
    img: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/gestion-des-parties-prenantes",
    category: "dirigeant",
  },
  {
    title: "Design Organisationnel & Transformation d'Entreprise",
    desc: "Maîtrisez le process et la méthodologie pour diagnostiquer une organisation et déployer son plan de transformation.",
    price: "$97",
    rating: 4.6,
    reviews: 1142,
    img: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=400&q=80",
    badge: "Premium",
    type: "Parcours",
    href: "https://www.managersity.co/bundles/design-organisationnel-optimise-transformation-culturelle-et-pilotage-efficace-du-changement-organi",
    category: "dirigeant",
  },

  // Management Commercial
  {
    title: "Dispositif & Outils de Pilotage de la Performance Commerciale",
    desc: "Plus de 50 outils, matrices, plans pour modéliser, planifier et orchestrer plus aisément la performance commerciale.",
    price: "$37",
    rating: 4.6,
    reviews: 645,
    img: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/dispositif-et-outils-de-pilotage-commercial",
    category: "management-commercial-4-0",
  },
  {
    title: "Réussir son Management Commercial",
    desc: "État d'Esprit, Dispositifs et méthodes de pilotage commercial pour les directeurs et managers commerciaux.",
    price: "$59",
    rating: 4.7,
    reviews: 389,
    img: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=400&q=80",
    badge: "Top noté",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/reussir-son-management-commercial",
    category: "management-commercial-4-0",
  },
  {
    title: "L'Art de Casser la Baraque pour les Commerciaux",
    desc: "Mindset, optimisation mentale et approche inédite pour intégrer la nouvelle psychologie de la vente.",
    price: "$27",
    rating: 4.5,
    reviews: 712,
    img: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/lart-de-casser-la-baraque-pour-les-commerciaux",
    category: "management-commercial-4-0",
  },

  // Management d'Équipe
  {
    title: "L'Art de Catalyser et Piloter la Performance",
    desc: "Les outils et méthodes pour scénariser, catalyser et orchestrer la performance au Day-to-Day.",
    price: "$59",
    rating: 4.7,
    reviews: 1873,
    img: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/lart-de-catalyser-et-piloter-la-performance",
    category: "management-d-equipe",
  },
  {
    title: "Management du Changement Organisationnel & Transformation Culturelle",
    desc: "Comment les leaders performants élaborent un plan de transformation et de mobilisation des équipes.",
    price: "$29",
    rating: 4.4,
    reviews: 298,
    img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/management-du-changement-organisationnel",
    category: "management-d-equipe",
  },

  // Management du Capital Humain
  {
    title: "IA pour Manager RH 5.0 : Le Cours Complet",
    desc: "Comprendre l'IA de A-Z avec une immersion dans les utilisations pratiques pour un manager RH.",
    price: "$99",
    rating: 4.6,
    reviews: 336,
    img: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/L-IA-pour-les-RH",
    category: "management-du-capital-humain",
  },

  // Développement Personnel
  {
    title: "Piloter sa Résilience et son Bien-être Personnel",
    desc: "État d'esprit et mécanismes inédits pour trouver son épanouissement et rester fort dans un monde en tension.",
    price: "$27",
    rating: 4.6,
    reviews: 523,
    img: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=400&q=80",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/piloter-sa-resilience-et-son-ben-etre-personnel",
    category: "developpement-personnel",
  },
  {
    title: "Gestion du Stress : Méthodes Inédites pour Anticiper les Pressions",
    desc: "Méthodes inédites d'organisation pour prévenir et gérer intelligemment les moments de stress.",
    price: "$27",
    rating: 4.7,
    reviews: 841,
    img: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/gestion-du-stress-et-des-pressions",
    category: "developpement-personnel",
  },
  {
    title: "Développer son Potentiel et se Mettre à la Dimension de ses Rêves",
    desc: "Prendre en main sa vie et sa carrière, prendre conscience de son potentiel et réaliser la meilleure version de soi-même.",
    price: "$27",
    rating: 4.8,
    reviews: 1200,
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    badge: "Top noté",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/developper-son-potentiel-et-se-mettre-a-la-dimension-de-ses-reves",
    category: "developpement-personnel",
  },
  {
    title: "Intelligence Émotionnelle & Gestion des Relations avec les Autres",
    desc: "Travailler son self-management, devenir confiant et autodéterminé, maîtriser ses émotions.",
    price: "$27",
    rating: 4.6,
    reviews: 654,
    img: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=400&q=80",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/intelligence-emotionnelle-et-gestion-des-relations-avec-les-autres",
    category: "developpement-personnel",
  },
  {
    title: "Méthodes de Gestion du Temps & de Discipline Personnelles pour les Pro",
    desc: "Méthodes simples et inédites pour tirer le meilleur parti de ses journées et délivrer des performances records.",
    price: "$59",
    rating: 4.7,
    reviews: 912,
    img: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/methodes-de-gestion-du-temps",
    category: "developpement-personnel",
  },
  {
    title: "L'Art de se Fixer les Objectifs et les Atteindre",
    desc: "L'état d'esprit et la méthodologie avec des outils pratiques pour vous fixer n'importe quel type d'objectif.",
    price: "$27",
    rating: 4.5,
    reviews: 478,
    img: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=400&q=80",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/lart-de-se-fixer-des-objectifs-et-les-atteindre",
    category: "developpement-personnel",
  },

  // Entrepreneuriat
  {
    title: "Le Game de la Stratégie & Disruption Marché",
    desc: "Affinement de la profondeur stratégique, multiplication de vos coups d'avance et disruption de vos marchés.",
    price: "$97",
    rating: 4.7,
    reviews: 512,
    img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=400&q=80",
    badge: "Premium",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/le-game-de-la-strategie-et-disruption-marche",
    category: "entrepreneuriat",
  },
  {
    title: "Design Organisationnel & Transformation d'Entreprise",
    desc: "Process et méthodologie pour diagnostiquer une organisation et déployer son plan de transformation.",
    price: "$97",
    rating: 4.6,
    reviews: 1142,
    img: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=400&q=80",
    badge: "Premium",
    type: "Parcours",
    href: "https://www.managersity.co/bundles/design-organisationnel-optimise-transformation-culturelle-et-pilotage-efficace-du-changement-organi",
    category: "entrepreneuriat",
  },

  // Vendeur Elite
  {
    title: "L'Art de Casser la Baraque pour les Commerciaux",
    desc: "Mindset, optimisation mentale et approche inédite pour la nouvelle psychologie de la vente.",
    price: "$27",
    rating: 4.5,
    reviews: 712,
    img: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/lart-de-casser-la-baraque-pour-les-commerciaux",
    category: "vendeur-elite-expert-4-0",
  },
  {
    title: "Dispositif & Outils de Pilotage de la Performance Commerciale",
    desc: "Plus de 50 outils et matrices pour modéliser, planifier et orchestrer la performance commerciale.",
    price: "$37",
    rating: 4.6,
    reviews: 645,
    img: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=400&q=80",
    badge: "Top noté",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/dispositif-et-outils-de-pilotage-commercial",
    category: "vendeur-elite-expert-4-0",
  },

  // MasterCourses
  {
    title: "Parcours Dirigeant Certifié (PDC)",
    desc: "Acquérez les compétences clés pour briller en tant que dirigeant et réussir votre promotion.",
    price: "$519",
    rating: 4.8,
    reviews: 2724,
    img: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Parcours",
    href: "https://www.managersity.co/bundles/parcours-dirigeant-certifie-pdc",
    category: "mastercourses",
  },
  {
    title: "Design Organisationnel & Transformation d'Entreprise",
    desc: "Maîtrisez le process et la méthodologie pour diagnostiquer et transformer une organisation.",
    price: "$97",
    rating: 4.6,
    reviews: 1142,
    img: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
    badge: "Premium",
    type: "Parcours",
    href: "https://www.managersity.co/bundles/design-organisationnel-optimise-transformation-culturelle-et-pilotage-efficace-du-changement-organi",
    category: "mastercourses",
  },
  {
    title: "Maturité Managériale & Enjeux de Direction Générale",
    desc: "Pour les membres de CODIR qui doivent démontrer de l'excellence Top Executive.",
    price: "$97",
    rating: 4.7,
    reviews: 893,
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/maturite-manageriale-et-enjeux-de-direction-generale",
    category: "mastercourses",
  },
  {
    title: "Gestion des Parties Prenantes & Networking Diplomatique",
    desc: "Lorsqu'un dirigeant échoue, c'est parce qu'il a échoué dans ses relations avec ses parties prenantes.",
    price: "$97",
    rating: 4.5,
    reviews: 432,
    img: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=400&q=80",
    badge: "Bestseller",
    type: "Cours",
    href: "https://www.managersity.co/products/courses/gestion-des-parties-prenantes",
    category: "mastercourses",
  },
];

export type CategoryMeta = {
  label: string;
  slug: string;
  description: string;
  icon: string;
  color: string;
};

export const categoryMeta: Record<string, CategoryMeta> = {
  "transformation-digitale-4-0": {
    label: "Transformation Digitale 4.0",
    slug: "transformation-digitale-4-0",
    description: "Maîtrisez l'IA et la digitalisation pour transformer votre organisation et votre carrière.",
    icon: "⚡",
    color: "from-cyan-600 to-sky-400",
  },
  dirigeant: {
    label: "Dirigeant",
    slug: "dirigeant",
    description: "Développez votre excellence en tant que dirigeant et prenez votre organisation à un niveau supérieur.",
    icon: "👑",
    color: "from-violet-600 to-purple-400",
  },
  "management-commercial-4-0": {
    label: "Management Commercial 4.0",
    slug: "management-commercial-4-0",
    description: "Pilotez votre performance commerciale avec les meilleures méthodes et outils du marché.",
    icon: "📈",
    color: "from-blue-600 to-blue-400",
  },
  "management-d-equipe": {
    label: "Management d'Équipe",
    slug: "management-d-equipe",
    description: "Renforcez votre leadership et animez vos équipes pour atteindre l'excellence opérationnelle.",
    icon: "👥",
    color: "from-teal-600 to-teal-400",
  },
  "management-du-capital-humain": {
    label: "Management du Capital Humain",
    slug: "management-du-capital-humain",
    description: "Optimisez la gestion des talents, la culture et le développement de vos ressources humaines.",
    icon: "🤝",
    color: "from-rose-600 to-pink-400",
  },
  "developpement-personnel": {
    label: "Développement Personnel",
    slug: "developpement-personnel",
    description: "Libérez votre potentiel, gérez vos émotions et construisez une vie professionnelle épanouissante.",
    icon: "🌱",
    color: "from-green-600 to-emerald-400",
  },
  entrepreneuriat: {
    label: "Entrepreneuriat",
    slug: "entrepreneuriat",
    description: "Structurez et faites croître votre entreprise avec les meilleures stratégies et outils.",
    icon: "🚀",
    color: "from-orange-500 to-amber-500",
  },
  "vendeur-elite-expert-4-0": {
    label: "Vendeur Elite Expert 4.0",
    slug: "vendeur-elite-expert-4-0",
    description: "Maîtrisez les techniques de vente avancées pour dépasser vos objectifs commerciaux.",
    icon: "🏆",
    color: "from-yellow-600 to-amber-400",
  },
  mastercourses: {
    label: "MasterCourses",
    slug: "mastercourses",
    description: "Les parcours d'excellence pour les dirigeants et hauts potentiels de l'Afrique francophone.",
    icon: "👑",
    color: "from-gray-700 to-gray-500",
  },
};
