export type CourseDetail = {
  slug: string;
  title: string;
  category: string;
  price: number;
  originalPrice?: number;
  shopUrl: string;
  enrollUrl?: string;
  tagline: string;
  totalChapters?: number;
  totalLessons?: number;
  learns?: string[];
  chapters?: string[];
  benefits?: { title: string; desc: string }[];
};

export const COURSES: CourseDetail[] = [

  // ── INTELLIGENCE ARTIFICIELLE ─────────────────────────────────────────────

  {
    slug: "ia-pour-les-managers",
    title: "Intelligence Artificielle pour les Managers",
    category: "Intelligence Artificielle",
    price: 59000,
    originalPrice: 197000,
    shopUrl: "https://shop.managersity.com/produit/ia-pour-les-managers/",
    enrollUrl: "https://www.managersity.co/enroll/3468759",
    tagline: "Comprendre l'IA de A-Z avec une immersion concrète dans les utilisations pratiques pour booster la productivité et les performances de votre équipe.",
    totalChapters: 3,
    totalLessons: 39,
    learns: [
      "Utiliser des outils d'IA (ChatGPT, Copilot, Notion AI…) pour rédiger, synthétiser et analyser",
      "Gagner du temps sur les réunions, comptes-rendus, mails et feedbacks",
      "Automatiser des tâches clés (RH, planning, reporting…)",
      "Créer un agent IA sans coder pour vous assister au quotidien",
      "Coacher vos équipes dans un contexte hybride (humains + IA)",
      "Adopter une posture de leadership augmenté par l'IA",
    ],
    chapters: [
      "Introduction : Comprendre l'IA pour les managers (origine, écosystème, applications)",
      "Partie 1 : De l'essoufflement managérial à l'optimisation managériale augmentée par l'IA",
      "Partie 2 : Manager efficacement son équipe à l'ère de l'IA",
    ],
    benefits: [
      {
        title: "Comprendre l'IA sans être tech",
        desc: "Pas besoin d'être ingénieur pour comprendre et utiliser l'intelligence artificielle. La formation vous explique, en termes simples, comment fonctionne l'IA et comment l'appliquer dans votre rôle de manager.",
      },
      {
        title: "L'IA au service du quotidien managérial",
        desc: "L'IA va vous aider à automatiser vos tâches répétitives, mieux organiser vos réunions, rédiger vos comptes-rendus et suivre les performances de votre équipe avec moins d'effort.",
      },
      {
        title: "Devenir un leader augmenté avec l'IA",
        desc: "L'IA ne remplace pas le manager, elle le renforce. En l'utilisant comme un copilote, vous développez une posture de leadership plus stratégique, plus réactive et plus humaine.",
      },
    ],
  },

  {
    slug: "ia-pour-sales-managers-5-0-le-cours-complet",
    title: "IA pour Sales Managers 5.0 : Le Cours Complet",
    category: "Intelligence Artificielle",
    price: 59000,
    originalPrice: 197000,
    shopUrl: "https://shop.managersity.com/produit/ia-pour-sales-managers-5-0-le-cours-complet/",
    enrollUrl: "https://www.managersity.co/enroll/3500554",
    tagline: "Comment les managers commerciaux innovants utilisent la DATA, l'IA et la Technologie pour avoir plusieurs coups d'avance sur leurs concurrents.",
    totalChapters: 5,
    totalLessons: 39,
    learns: [
      "Utiliser des outils d'IA (ChatGPT, Power BI Intelligence, Tableau AI…) pour analyser, décider et communiquer",
      "Automatiser le reporting, l'analyse de performance commerciale et la veille concurrentielle",
      "Créer des dashboards prédictifs sans coder pour piloter votre performance en temps réel",
      "Anticiper les tendances marché, optimiser les choix et le coaching des commerciaux",
      "Transformer votre pilotage commercial et accompagner vos équipes dans l'adoption de l'IA",
      "Adopter une posture de leader commercial disruptif augmenté par l'IA",
    ],
    chapters: [
      "Introduction : L'IA ne va pas remplacer les commerciaux mais les managers qui pilotent à l'ancienne",
      "Partie 1 : Intelligence artificielle, DATA et pilotage de la performance commerciale",
      "Partie 2 : Immersion dans l'univers IA — ce que le manager commercial doit savoir",
      "Partie 3 : De l'essoufflement à l'optimisation de l'excellence managériale commerciale",
      "Partie 4 : Implémenter et intégrer l'IA à son management commercial de A à Z",
    ],
    benefits: [
      {
        title: "Automatiser les tâches répétitives et libérer du temps stratégique",
        desc: "Apprenez à utiliser l'IA comme levier de croissance accessible, rentable et différenciant pour dépasser vos concurrents et réaliser vos quotas bien plus vite.",
      },
      {
        title: "Optimiser le pilotage commercial en temps réel",
        desc: "L'IA transforme votre pilotage : anticiper les tendances marché, optimiser votre chaîne de valeur, personnaliser l'expérience client et accélérer vos prises de décision.",
      },
      {
        title: "Personnaliser et automatiser le coaching commercial",
        desc: "En utilisant l'IA comme copilote intelligent, vous développez un leadership plus anticipatif, plus agile et plus innovant face aux défis commerciaux.",
      },
    ],
  },

  {
    slug: "ia-pour-les-professionnels",
    title: "IA pour Assistants & Professionnels : Le Cours Complet",
    category: "Intelligence Artificielle",
    price: 29000,
    originalPrice: 97000,
    shopUrl: "https://shop.managersity.com/produit/ia-pour-les-professionnels/",
    enrollUrl: "https://www.managersity.co/enroll/3499319",
    tagline: "Comment les professionnels qui maîtrisent l'IA produisent en 2 heures ce qui prend 2 jours à leurs collègues. L'IA devient votre copilote.",
    totalChapters: 1,
    totalLessons: 5,
    learns: [
      "Utiliser les outils d'IA (ChatGPT, Claude, Gemini, Copilot, Perplexity) pour rédiger, analyser et décider 3x plus vite",
      "Écrire des prompts structurés avec le framework RCTCF pour obtenir des résultats exploitables du premier coup",
      "Appliquer l'IA à votre métier spécifique avec des cas d'usage concrets (finance, commercial, RH, juridique)",
      "Créer vos propres assistants IA permanents qui connaissent votre entreprise et travaillent pour vous 24h/24",
      "Classer vos tâches avec le framework SCRA pour identifier où l'IA vous fait gagner le plus de temps",
      "Déployer l'IA dans votre équipe avec un plan de 90 jours concret et mesurable",
    ],
    chapters: [
      "Module 1 : L'IA offre une opportunité historique à tous les professionnels",
    ],
    benefits: [
      {
        title: "Comprendre l'IA sans être tech",
        desc: "Pas besoin d'être ingénieur pour transformer votre façon de travailler. La formation vous explique l'IA en termes simples et vous montre comment l'appliquer concrètement dès demain.",
      },
      {
        title: "Maîtriser l'art du prompt et créer vos assistants IA permanents",
        desc: "Découvrez le framework RCTCF pour obtenir des résultats excellents du premier coup, et créez vos propres assistants IA qui travaillent pour vous 24h/24.",
      },
      {
        title: "Déployer l'IA dans votre équipe et votre organisation",
        desc: "Apprenez à chiffrer le ROI, à accompagner vos équipes dans l'adoption de l'IA et à mettre en place une gouvernance responsable avec un plan de 90 jours.",
      },
    ],
  },

  {
    slug: "ia-pour-les-rh",
    title: "IA pour Manager RH 5.0 : Le Cours Complet",
    category: "Intelligence Artificielle",
    price: 59000,
    originalPrice: 197000,
    shopUrl: "https://shop.managersity.com/produit/ia-pour-les-rh/",
    enrollUrl: "https://www.managersity.co/enroll/3499149",
    tagline: "Transformez vos RH à l'ère de l'IA. Sourcing automatisé, prédiction des départs, onboarding personnalisé : l'IA devient votre copilote RH.",
    totalChapters: 4,
    totalLessons: 39,
    learns: [
      "Utiliser des outils d'IA (ChatGPT, LinkedIn Talent Insights, HiBob AI…) pour recruter, évaluer et communiquer",
      "Automatiser le sourcing, la sélection CV, les entretiens et l'onboarding collaborateur",
      "Créer des chatbots RH sans coder pour répondre aux questions des collaborateurs",
      "Analyser l'engagement, prédire les départs et optimiser la rétention des talents",
      "Personnaliser les parcours de formation et de développement des compétences",
      "Adopter une posture de RH Business Partner augmenté par l'IA",
    ],
    chapters: [
      "Introduction : L'IA et la DATA sont une opportunité pour les opérations RH répétitives et la stratégie",
      "Partie 1 : Comprendre l'IA pour les managers (origine, écosystème, applications)",
      "Partie 2 : De l'essoufflement managérial à l'optimisation managériale augmentée par l'IA",
      "Partie 3 : Manager efficacement son équipe RH à l'ère de l'IA",
    ],
    benefits: [
      {
        title: "Comprendre l'IA sans être data scientist",
        desc: "Pas besoin d'être tech pour révolutionner vos RH. La formation vous explique l'IA en termes simples, avec des applications concrètes dans l'univers RH.",
      },
      {
        title: "L'IA au service du quotidien RH",
        desc: "L'IA automatise le sourcing candidats, personnalise les parcours d'onboarding, analyse l'engagement des équipes et optimise vos processus d'évaluation.",
      },
      {
        title: "Devenir un RH leader augmenté avec l'IA",
        desc: "L'IA ne remplace pas le RH, elle le renforce. Développez une approche RH plus stratégique, plus prédictive et plus humaine pour anticiper les besoins de vos talents.",
      },
    ],
  },

  {
    slug: "kit-du-manager-augmente-ia",
    title: "Kit du Manager Augmenté IA",
    category: "Intelligence Artificielle",
    price: 39000,
    originalPrice: 199000,
    shopUrl: "https://shop.managersity.com/produit/kit-du-manager-augmente-ia/",
    tagline: "Boîte à outils complète pour le manager moderne : templates, prompts et guides pratiques pour utiliser l'IA efficacement au quotidien.",
  },

  {
    slug: "lia-pour-les-dirigeants-5-0-le-cours-complet",
    title: "L'IA pour les Dirigeants 5.0 : Le Cours Complet",
    category: "Intelligence Artificielle",
    price: 97000,
    originalPrice: 297000,
    shopUrl: "https://shop.managersity.com/produit/lia-pour-les-dirigeants-5-0-le-cours-complet/",
    tagline: "Comment les DG et dirigeants 5.0 utilisent l'IA pour optimiser le cadrage stratégique, la planification et le pilotage de leurs organisations.",
  },

  // ── PACKS PHARES ──────────────────────────────────────────────────────────

  {
    slug: "parcours-dirigeant",
    title: "Parcours Dirigeant Certifié",
    category: "Packs Phares",
    price: 304900,
    originalPrice: 597000,
    shopUrl: "https://shop.managersity.com/produit/parcours-dirigeant/",
    tagline: "Le parcours complet et certifiant pour développer votre excellence de direction — stratégie, leadership, finance, capital humain et transformation.",
  },
  {
    slug: "parcours-dirigeant-delite",
    title: "Parcours Dirigeant d'Élite",
    category: "Packs Phares",
    price: 249000,
    shopUrl: "https://shop.managersity.com/produit/parcours-dirigeant-delite/",
    tagline: "L'itinéraire d'excellence pour les dirigeants ambitieux : stratégie, leadership, impact. Tout ce qu'il faut pour exceller au sommet.",
  },
  {
    slug: "parcours-ia-performance-professionnelle-delite",
    title: "Parcours IA & Performance Professionnelle d'Élite",
    category: "Packs Phares",
    price: 99000,
    shopUrl: "https://shop.managersity.com/produit/parcours-ia-performance-professionnelle-delite/",
    tagline: "Maîtrisez l'IA et boostez votre performance professionnelle avec ce parcours élite couvrant tous les outils et méthodes IA essentiels.",
  },
  {
    slug: "parcours-manager-delite",
    title: "Parcours Manager d'Élite",
    category: "Packs Phares",
    price: 79000,
    shopUrl: "https://shop.managersity.com/produit/parcours-manager-delite/",
    tagline: "Devenez un manager d'élite avec ce parcours complet couvrant toutes les dimensions du management moderne : équipe, performance, communication et leadership.",
  },
  {
    slug: "parcours-manager-commercial-delite",
    title: "Parcours Manager Commercial d'Élite",
    category: "Packs Phares",
    price: 79000,
    shopUrl: "https://shop.managersity.com/produit/parcours-manager-commercial-delite/",
    tagline: "Parcours complet pour exceller dans le management commercial à l'ère digitale : pipeline, coaching commercial, pilotage et performance.",
  },
  {
    slug: "parcours-rh-capital-humain-delite",
    title: "Parcours RH & Capital Humain d'Élite",
    category: "Packs Phares",
    price: 79000,
    shopUrl: "https://shop.managersity.com/produit/parcours-rh-capital-humain-delite/",
    tagline: "Maîtrisez les enjeux RH modernes et devenez un expert du capital humain : acquisition, engagement, développement et fidélisation des talents.",
  },
  {
    slug: "parcours-clarte-performance-personnelle-delite",
    title: "Parcours Clarté & Performance Personnelle d'Élite",
    category: "Packs Phares",
    price: 59000,
    shopUrl: "https://shop.managersity.com/produit/parcours-clarte-performance-personnelle-delite/",
    tagline: "Gagnez en clarté, organisation et performance personnelle avec ce parcours holistique couvrant gestion du temps, objectifs et résilience.",
  },

  // ── MANAGEMENT D'ÉQUIPE ───────────────────────────────────────────────────

  {
    slug: "parcours-manager-dequipe-4-0-vvip",
    title: "Parcours Manager d'Équipe 4.0 VVIP",
    category: "Management d'Équipe",
    price: 297000,
    originalPrice: 397000,
    shopUrl: "https://shop.managersity.com/produit/parcours-manager-dequipe-4-0-vvip/",
    tagline: "Le parcours VVIP le plus complet pour maîtriser toutes les dimensions du management d'équipe 4.0 : leadership, performance, coaching et transformation.",
  },
  {
    slug: "parcours-middle-manager-4-0",
    title: "Parcours Middle Manager 4.0",
    category: "Management d'Équipe",
    price: 127000,
    shopUrl: "https://shop.managersity.com/produit/parcours-middle-manager-4-0/",
    tagline: "Devenez un middle manager d'exception : leadership situationnel, gestion d'équipe, communication ascendante et performance opérationnelle.",
  },
  {
    slug: "parcours-manager-dequipe-4-0-vvip-3-tranches",
    title: "Parcours Manager d'Équipe 4.0 VVIP — 3 tranches",
    category: "Management d'Équipe",
    price: 120000,
    shopUrl: "https://shop.managersity.com/produit/parcours-manager-dequipe-4-0-vvip-3-tranches/",
    tagline: "Le parcours VVIP complet en 3 versements pour booster vos compétences managériales sans contrainte financière.",
  },
  {
    slug: "parcours-manager-dequipe-4-0-vip",
    title: "Parcours Manager d'Équipe 4.0 VIP",
    category: "Management d'Équipe",
    price: 97000,
    originalPrice: 159000,
    shopUrl: "https://shop.managersity.com/produit/parcours-manager-dequipe-4-0-vip/",
    tagline: "Parcours VIP pour développer toutes vos compétences de manager d'équipe à l'ère 4.0 : leadership, cohésion, performance et bien-être.",
  },

  // ── PARCOURS DIRIGEANT ────────────────────────────────────────────────────

  {
    slug: "pack-25-ebooks-pour-dirigeant",
    title: "PACK 25 EBOOKS POUR DIRIGEANT",
    category: "Parcours Dirigeant",
    price: 99000,
    originalPrice: 159000,
    shopUrl: "https://shop.managersity.com/produit/pack-25-ebooks-pour-dirigeant/",
    tagline: "25 ebooks essentiels pour les dirigeants : stratégie, leadership, finance, transformation digitale et capital humain. Une bibliothèque complète.",
  },
  {
    slug: "maturite-manageriale-enjeux-de-direction-generale",
    title: "Maturité Managériale & Enjeux de Direction Générale",
    category: "Parcours Dirigeant",
    price: 59000,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/maturite-manageriale-enjeux-de-direction-generale/",
    enrollUrl: "https://www.managersity.co/enroll/3234141",
    tagline: "Que vous visiez le poste de DG ou y soyez déjà, ce module révèle le travail d'optimisation indispensable pour exceller à la direction générale.",
    totalChapters: 4,
    totalLessons: 35,
    learns: [
      "Comprendre les enjeux réels du poste de Directeur Général et de membre de CODIR",
      "Identifier ce que les DG qui réussissent font différemment de ceux qui échouent",
      "Procéder aux optimisations nécessaires pour vous qualifier pour le poste de top dirigeant",
      "Développer la posture, le mindset et les compétences d'une excellence dirigeante",
      "Définir vos objectifs stratégiques et piloter vos enjeux avec méthode et clarté",
      "Vous différencier et créer une valeur ajoutée unique en tant que dirigeant",
    ],
    chapters: [
      "Introduction : À la dimension dirigeant ?",
      "Partie 1 : Prendre conscience des enjeux de direction générale",
      "Partie 2 : Passer à la dimension dirigeant",
      "Partie 3 : Faire la différence en tant que dirigeant",
    ],
    benefits: [
      {
        title: "Prendre conscience des enjeux de direction générale",
        desc: "Savoir ce que cela suppose d'être membre de CODIR ou DG et les enjeux à porter quand on y est. Sortir des illusions pour voir la réalité du poste.",
      },
      {
        title: "S'élever à la dimension dirigeant",
        desc: "Procéder aux optimisations et ajustements nécessaires pour se qualifier pour le poste de Top Manager et réussir en tant que Directeur Général.",
      },
      {
        title: "S'organiser pour piloter les enjeux stratégiques",
        desc: "Définir des objectifs clairs, prioriser vos tâches par urgence et déléguer les responsabilités de manière appropriée pour maximiser votre impact.",
      },
    ],
  },
  {
    slug: "design-organisationnel-transformation-dentreprise",
    title: "Design Organisationnel & Transformation d'Entreprise",
    category: "Parcours Dirigeant",
    price: 57000,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/design-organisationnel-transformation-dentreprise/",
    tagline: "Maîtrisez la méthodologie pour diagnostiquer une organisation, évaluer ses capacités et déployer sa transformation avec succès.",
  },
  {
    slug: "intelligence-emotionnelle-mecanismes-decisionnels-pour-les-dirigeants",
    title: "Jeu Intérieur du Leadership, Intelligence Émotionnelle & Mécanismes Décisionnels",
    category: "Parcours Dirigeant",
    price: 34900,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/intelligence-emotionnelle-mecanismes-decisionnels-pour-les-dirigeants/",
    tagline: "Développez votre intelligence émotionnelle et maîtrisez vos mécanismes décisionnels pour diriger avec impact dans tous les contextes.",
  },
  {
    slug: "management-de-projet-et-realisation-des-objectifs-strategiques",
    title: "Management de Projet & Réalisation des Objectifs Stratégiques",
    category: "Parcours Dirigeant",
    price: 29000,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/management-de-projet-et-realisation-des-objectifs-strategiques/",
    tagline: "Pilotez vos projets stratégiques avec méthode et faites de l'atteinte des objectifs un processus structuré et reproductible.",
  },
  {
    slug: "management-strategique-du-capital-humain",
    title: "Management Stratégique du Capital Humain",
    category: "Parcours Dirigeant",
    price: 29000,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/management-strategique-du-capital-humain/",
    tagline: "Faites du capital humain un levier de performance stratégique : acquisition de talents, engagement, montée en compétences et rétention.",
  },
  {
    slug: "modelisation-maitrise-financieres-pour-les-dirigeants",
    title: "Modélisation & Maîtrise Financières pour les Dirigeants",
    category: "Parcours Dirigeant",
    price: 29000,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/modelisation-maitrise-financieres-pour-les-dirigeants/",
    tagline: "Maîtrisez les fondamentaux financiers pour prendre des décisions éclairées, piloter la performance et dialoguer avec les investisseurs.",
  },
  {
    slug: "gestion-des-parties-prenantes-networking-diplomatique-pour-les-dirigeants",
    title: "Gestion des Parties Prenantes & Networking Diplomatique pour les Dirigeants",
    category: "Parcours Dirigeant",
    price: 29900,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/gestion-des-parties-prenantes-networking-diplomatique-pour-les-dirigeants/",
    tagline: "Développez vos relations stratégiques et votre leadership diplomatique pour influencer vos parties prenantes et atteindre vos objectifs.",
  },
  {
    slug: "lart-de-casser-la-baraque-pour-les-commerciaux",
    title: "L'Art de Casser la Baraque pour les Commerciaux",
    category: "Parcours Dirigeant",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/lart-de-casser-la-baraque-pour-les-commerciaux/",
    tagline: "Les techniques et méthodes des commerciaux d'élite pour dépasser tous leurs objectifs de vente et créer une dynamique de performance durable.",
  },
  {
    slug: "developper-son-potentiel-et-se-mettre-a-la-dimension-de-ses-reves",
    title: "Développer son Potentiel et se Mettre à la Dimension de ses Rêves",
    category: "Parcours Dirigeant",
    price: 11990,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/developper-son-potentiel-et-se-mettre-a-la-dimension-de-ses-reves/",
    tagline: "Libérez votre potentiel, clarifiez votre vision et alignez votre vie professionnelle sur vos ambitions profondes et vos objectifs de carrière.",
  },

  // ── MODULES CERTIFIANTS ───────────────────────────────────────────────────

  {
    slug: "le-game-de-la-strategie-disruption-marche",
    title: "Le Game de la Stratégie & Disruption Marché",
    category: "Modules Certifiants",
    price: 57000,
    originalPrice: 97000,
    shopUrl: "https://shop.managersity.com/produit/le-game-de-la-strategie-disruption-marche/",
    tagline: "Maîtrisez les leviers de la stratégie et de la disruption pour positionner votre entreprise en avance et créer un avantage concurrentiel durable.",
  },
  {
    slug: "le-coaching-managerial-4-0",
    title: "Le Coaching Managérial 4.0",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/le-coaching-managerial-4-0/",
    tagline: "Devenez un manager-coach d'exception : techniques de coaching, feedbacks structurés et développement des talents pour une équipe haute performance.",
  },
  {
    slug: "reussir-son-management-commercial",
    title: "Réussir son Management Commercial",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/reussir-son-management-commercial/",
    tagline: "Les méthodes et outils pour piloter une équipe commerciale performante, atteindre les quotas et créer une culture de l'excellence commerciale.",
  },
  {
    slug: "reussir-avec-son-conseil-dadministration-et-son-groupe",
    title: "Réussir avec son Conseil d'Administration et son Groupe",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/reussir-avec-son-conseil-dadministration-et-son-groupe/",
    tagline: "Maîtrisez les dynamiques du conseil d'administration, renforcez votre gouvernance et créez une relation constructive avec vos actionnaires.",
  },
  {
    slug: "leadership-situationnel-intelligence-emotionnelle",
    title: "Leadership Situationnel & Intelligence Émotionnelle",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/leadership-situationnel-intelligence-emotionnelle/",
    tagline: "Adaptez votre style de leadership selon les situations et développez votre intelligence émotionnelle pour un management plus humain et efficace.",
  },
  {
    slug: "choix-complexes-mecanismes-decisionnels",
    title: "Choix Complexes & Mécanismes Décisionnels",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/choix-complexes-mecanismes-decisionnels/",
    tagline: "Prenez les bonnes décisions dans l'incertitude grâce aux mécanismes décisionnels des meilleurs leaders. Structurez vos choix complexes.",
  },
  {
    slug: "leadership-pouvoir-de-linfluence",
    title: "Leadership & Pouvoir de l'Influence",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/leadership-pouvoir-de-linfluence/",
    tagline: "Développez un leadership authentique et maîtrisez l'art d'influencer sans autorité formelle pour mobiliser vos équipes et partenaires.",
  },
  {
    slug: "structurer-et-piloter-une-vision-dentreprise",
    title: "Structurer et Piloter une Vision d'Entreprise",
    category: "Modules Certifiants",
    price: 27900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/structurer-et-piloter-une-vision-dentreprise/",
    tagline: "Définissez une vision ambitieuse, structurez-la en stratégie opérationnelle et mobilisez vos équipes autour d'un cap commun clair.",
  },
  {
    slug: "lart-de-structurer-et-optimiser-un-processus",
    title: "L'Art de Structurer et Optimiser un Processus",
    category: "Modules Certifiants",
    price: 21900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/lart-de-structurer-et-optimiser-un-processus/",
    tagline: "Cartographiez, simplifiez et optimisez vos processus pour gagner en efficacité opérationnelle et éliminer les sources de perte de performance.",
  },
  {
    slug: "dispositif-outils-de-pilotage-commercial",
    title: "Dispositif & Outils de Pilotage Commercial",
    category: "Modules Certifiants",
    price: 21900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/dispositif-outils-de-pilotage-commercial/",
    tagline: "Mettez en place les tableaux de bord et outils de suivi pour piloter votre performance commerciale avec précision et en temps réel.",
  },
  {
    slug: "reussir-le-job-de-manager-commercial",
    title: "Réussir le Job de Manager Commercial",
    category: "Modules Certifiants",
    price: 21900,
    originalPrice: 34900,
    shopUrl: "https://shop.managersity.com/produit/reussir-le-job-de-manager-commercial/",
    tagline: "Maîtrisez les fondamentaux du poste de manager commercial : animation d'équipe, pilotage du pipeline, coaching et atteinte des résultats.",
  },
  {
    slug: "batir-une-equipe-performante",
    title: "Bâtir une Équipe Performante",
    category: "Modules Certifiants",
    price: 19900,
    originalPrice: 59900,
    shopUrl: "https://shop.managersity.com/produit/batir-une-equipe-performante/",
    tagline: "Recrutez, onboardez, motivez et fidélisez les talents pour construire une équipe de haute performance et une culture de résultats.",
  },
  {
    slug: "management-du-changement-organisationnel",
    title: "Management du Changement Organisationnel",
    category: "Modules Certifiants",
    price: 19900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/management-du-changement-organisationnel/",
    tagline: "Pilotez la transformation de votre organisation en minimisant les résistances, en maximisant l'adoption et en préservant la performance.",
  },
  {
    slug: "methodes-de-gestion-du-temps-dorganisation-et-de-discipline-personnelle-pour-les-pros",
    title: "Méthodes de Gestion du Temps, d'Organisation et de Discipline Personnelle",
    category: "Modules Certifiants",
    price: 19900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/methodes-de-gestion-du-temps-dorganisation-et-de-discipline-personnelle-pour-les-pros/",
    tagline: "Maîtrisez votre temps, organisez vos priorités et développez une discipline personnelle de haut niveau pour performer durablement.",
  },
  {
    slug: "optimiser-sa-posture-manageriale",
    title: "Optimiser sa Posture Managériale",
    category: "Modules Certifiants",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/optimiser-sa-posture-manageriale/",
    tagline: "Identifiez et corrigez les comportements qui limitent votre impact managérial pour adopter une posture de leadership optimal.",
  },
  {
    slug: "gestion-du-stress-et-des-pressions",
    title: "Gestion du Stress et des Pressions",
    category: "Modules Certifiants",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/gestion-du-stress-et-des-pressions/",
    tagline: "Développez des stratégies concrètes pour gérer le stress professionnel, neutraliser les pressions et maintenir votre performance sous pression.",
  },
  {
    slug: "piloter-sa-resilience-et-son-bien-etre-personnel",
    title: "Piloter sa Résilience et son Bien-Être Personnel",
    category: "Modules Certifiants",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/piloter-sa-resilience-et-son-bien-etre-personnel/",
    tagline: "Construisez une résilience durable et pilotez votre bien-être pour performer sur le long terme tout en préservant votre équilibre personnel.",
  },

  // ── DÉVELOPPEMENT PERSONNEL ───────────────────────────────────────────────

  {
    slug: "intelligence-emotionnelle-gestion-des-relations-avec-les-autres",
    title: "Intelligence Émotionnelle & Gestion des Relations avec les Autres",
    category: "Développement Personnel",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/intelligence-emotionnelle-gestion-des-relations-avec-les-autres/",
    tagline: "Développez votre quotient émotionnel et améliorez la qualité de toutes vos relations professionnelles pour plus d'impact et d'harmonie.",
  },
  {
    slug: "lart-de-se-fixer-les-objectifs-les-atteindre-et-les-atteindre",
    title: "L'Art de se Fixer les Objectifs et les Atteindre",
    category: "Développement Personnel",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/lart-de-se-fixer-les-objectifs-les-atteindre-et-les-atteindre/",
    tagline: "La méthode éprouvée pour vous fixer des objectifs ambitieux, les planifier avec précision et les atteindre systématiquement.",
  },
  {
    slug: "etat-desprit-resilience-entrepreneuriale",
    title: "État d'Esprit & Résilience Entrepreneuriale",
    category: "Développement Personnel",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/etat-desprit-resilience-entrepreneuriale/",
    tagline: "Développez le mindset et la résilience d'un entrepreneur qui surmonte les obstacles, persévère et transforme les défis en opportunités.",
  },

  // ── TRANSFORMATION DIGITALE ───────────────────────────────────────────────

  {
    slug: "enjeux-business-methodologie-de-transformation-digitale",
    title: "Enjeux Business & Méthodologie de Transformation Digitale",
    category: "Transformation Digitale",
    price: 29900,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/enjeux-business-methodologie-de-transformation-digitale/",
    tagline: "Maîtrisez les enjeux et la méthodologie pour piloter la transformation digitale de votre organisation avec méthode et impact durable.",
  },
];
