export type Course = {
  title: string;
  desc: string;
  price: string;
  rating: number;
  reviews: number;
  img: string;
  badge?: string;
  type: "Cours" | "Parcours";
  href: string;
  category: string;
};

export const allCourses: Course[] = [
  // Intelligence Artificielle
  {
    title: "L'IA pour les Managers Commerciaux 5.0 : Le Cours Complet",
    desc: "Comment les managers commerciaux innovants utilisent la DATA, l'IA et la Technologie pour avoir plusieurs coups d'avance.",
    price: "$99",
    rating: 4.7,
    reviews: 1468,
    img: "/cours/ia-managers-commerciaux.png",
    badge: "Bestseller",
    type: "Cours",
    href: "/cours/ia-pour-sales-managers-5-0-le-cours-complet",
    category: "intelligence-artificielle",
  },
  {
    title: "IA pour Assistants & Professionnels : Le Cours Complet",
    desc: "Boostez votre carrière avec l'IA. Automatisation des tâches répétitives, création de contenu optimisée, productivité x3.",
    price: "$57",
    rating: 4.7,
    reviews: 2024,
    img: "/cours/ia-assistants-professionnels.png",
    badge: "Bestseller",
    type: "Cours",
    href: "/cours/ia-pour-les-professionnels",
    category: "intelligence-artificielle",
  },
  {
    title: "IA pour Manager RH 5.0 : Le Cours Complet",
    desc: "Comprendre l'IA de A-Z avec une bonne immersion dans les utilisations pratiques pour booster la productivité.",
    price: "$99",
    rating: 4.6,
    reviews: 336,
    img: "/cours/ia-manager-rh.png",
    badge: "Bestseller",
    type: "Cours",
    href: "/cours/ia-pour-les-rh",
    category: "intelligence-artificielle",
  },
  {
    title: "L'IA pour les DG et les Dirigeants 5.0 : Le Cours Complet",
    desc: "Comment les DG et dirigeants 5.0 utilisent la DATA, l'IA et la Technologie pour optimiser le cadrage stratégique.",
    price: "$179",
    rating: 4.8,
    reviews: 92,
    img: "/cours/ia-dg-dirigeants.png",
    badge: "Top noté",
    type: "Cours",
    href: "/cours/lia-pour-les-dirigeants-5-0-le-cours-complet",
    category: "intelligence-artificielle",
  },
  {
    title: "Intelligence Artificielle pour les Managers",
    desc: "Comprendre l'IA de A-Z avec une immersion dans les utilisations pratiques pour booster la productivité d'un manager.",
    price: "$99",
    rating: 4.7,
    reviews: 403,
    img: "/cours/ia-pour-managers.png",
    badge: "Bestseller",
    type: "Cours",
    href: "/cours/ia-pour-les-managers",
    category: "intelligence-artificielle",
  },

  // Transformation Digitale 4.0
  {
    title: "Enjeux Business & Méthodologie de Transformation Digitale",
    desc: "Partir des besoins de réalisation des objectifs stratégiques et d'optimisation de l'excellence opérationnelle et clarifier…",
    price: "$47",
    rating: 4.6,
    reviews: 356,
    img: "/cours/enjeux-business-transformation.png",
    type: "Cours",
    href: "/cours/enjeux-business-methodologie-de-transformation-digitale",
    category: "transformation-digitale-4-0",
  },

  // Dirigeant
  {
    title: "Parcours Dirigeant Certifié (PDC)",
    desc: "Acquérez les compétences clés pour briller en tant que dirigeant et réussir votre promotion.",
    price: "$519",
    rating: 4.8,
    reviews: 2724,
    img: "/cours/parcours-dirigeant-certifie.png",
    badge: "Bestseller",
    type: "Parcours",
    href: "/cours/parcours-dirigeant",
    category: "dirigeant",
  },
  {
    title: "Le Game de la Stratégie & Disruption Marché",
    desc: "Tout ce que vous avez besoin de savoir pour affiner votre profondeur stratégique et disrupter vos marchés.",
    price: "$97",
    rating: 4.7,
    reviews: 512,
    img: "/cours/game-strategie-disruption.jpg",
    badge: "Premium",
    type: "Cours",
    href: "/cours/le-game-de-la-strategie-disruption-marche",
    category: "dirigeant",
  },
  {
    title: "Choix Complexes & Mécanismes Décisionnels",
    desc: "Modèles décisionnels pour identifier les signaux critiques, se poser les bonnes questions et prendre des décisions complexes.",
    price: "$59",
    rating: 4.6,
    reviews: 278,
    img: "/cours/choix-complexes-decisionnels.jpeg",
    type: "Cours",
    href: "/cours/choix-complexes-mecanismes-decisionnels",
    category: "dirigeant",
  },
  {
    title: "Leadership Situationnel & Intelligence Émotionnelle pour les Dirigeants",
    desc: "Comment les grands leaders abordent les situations complexes avec hauteur, intelligence émotionnelle.",
    price: "$59",
    rating: 4.8,
    reviews: 389,
    img: "/cours/leadership-situationnel-intelligence-emotionnelle.jpg",
    badge: "Top noté",
    type: "Cours",
    href: "/cours/leadership-situationnel-intelligence-emotionnelle",
    category: "dirigeant",
  },
  {
    title: "Maturité Managériale et Enjeux de Direction Générale",
    desc: "Pour les membres de CODIR qui doivent démontrer de l'excellence Top Executive.",
    price: "$97",
    rating: 4.7,
    reviews: 893,
    img: "/cours/maturite-manageriale.png",
    badge: "Bestseller",
    type: "Cours",
    href: "/cours/maturite-manageriale-enjeux-de-direction-generale",
    category: "dirigeant",
  },
  {
    title: "Gestion des Parties Prenantes & Networking Diplomatique pour les Dirigeants",
    desc: "Lorsqu'un dirigeant échoue, c'est parce qu'il a échoué dans ses relations avec ses parties prenantes.",
    price: "$97",
    rating: 4.5,
    reviews: 432,
    img: "/cours/gestion-parties-prenantes.png",
    badge: "Bestseller",
    type: "Cours",
    href: "/cours/gestion-des-parties-prenantes-networking-diplomatique-pour-les-dirigeants",
    category: "dirigeant",
  },
  {
    title: "Design Organisationnel & Transformation d'Entreprise",
    desc: "Maîtrisez le process et la méthodologie pour diagnostiquer une organisation et déployer son plan de transformation.",
    price: "$97",
    rating: 4.6,
    reviews: 1142,
    img: "/cours/design-organisationnel.jpeg",
    badge: "Premium",
    type: "Parcours",
    href: "/cours/design-organisationnel-transformation-dentreprise",
    category: "dirigeant",
  },
  {
    title: "Réussir avec son Conseil d'Administration et son Groupe",
    desc: "Nouvel état d'Esprit, Conscience Politique et Méthodes Optimisée pour comprendre la dynamique d'un conseil d'administration.",
    price: "$59",
    rating: 4.6,
    reviews: 312,
    img: "/cours/reussir-conseil-administration.png",
    type: "Cours",
    href: "/cours/reussir-avec-son-conseil-dadministration-et-son-groupe",
    category: "dirigeant",
  },
  {
    title: "L'Art de Structurer et Optimiser un Processus",
    desc: "Structurer et optimiser ses journées de manager commercial pour délivrer plus stratégiquement les quotas de vente fixée.",
    price: "$37",
    rating: 4.5,
    reviews: 287,
    img: "/cours/structurer-optimiser-processus.jpeg",
    type: "Cours",
    href: "/cours/lart-de-structurer-et-optimiser-un-processus",
    category: "dirigeant",
  },
  {
    title: "Management du Changement Organisationnel & Transformation Culturelle",
    desc: "Comment les leaders performants partent des contraintes culturelles et structurelles pour élaborer un plan de transformation.",
    price: "$29.90",
    rating: 4.4,
    reviews: 298,
    img: "/cours/management-changement.jpeg",
    type: "Cours",
    href: "/cours/management-du-changement-organisationnel",
    category: "dirigeant",
  },
  {
    title: "Pack 25 Ebooks pour Dirigeant et Futur Dirigeant",
    desc: "25 ebooks sur le top management, le management, le leadership et le développement personnel pour vous accompagner.",
    price: "$159",
    rating: 4.7,
    reviews: 534,
    img: "/cours/pack-25-ebooks.png",
    type: "Cours",
    href: "/cours/pack-25-ebooks-pour-dirigeant",
    category: "dirigeant",
  },
  {
    title: "Modélisation et Maîtrise Financière pour les Dirigeants",
    desc: "Comment les chiffres sont faits ? Comment partir des objectifs stratégiques et des ambitions financières à la modélisation.",
    price: "$47",
    rating: 4.6,
    reviews: 378,
    img: "/cours/modelisation-financiere.png",
    type: "Cours",
    href: "/cours/modelisation-maitrise-financieres-pour-les-dirigeants",
    category: "dirigeant",
  },
  {
    title: "Réussir le Design Organisationnel",
    desc: "Comment s'assurer qu'une entreprise est à la dimension requise pour atteindre ses objectifs stratégiques ? Elle doit atteindre…",
    price: "$37",
    rating: 4.5,
    reviews: 256,
    img: "/cours/reussir-design-organisationnel.png",
    type: "Cours",
    href: "/cours/management-de-projet-et-realisation-des-objectifs-strategiques",
    category: "dirigeant",
  },
  {
    title: "Jeu Intérieur du Leadership, Intelligence Émotionnelle & Mécanismes Décisionnels pour les Dirigeants",
    desc: "Pour les dirigeants sous tensions qui doivent gérer des situations complexes et opérer des choix pesants à longueur de journée.",
    price: "$97",
    rating: 4.7,
    reviews: 445,
    img: "/cours/jeu-interieur-leadership.png",
    type: "Cours",
    href: "/cours/intelligence-emotionnelle-mecanismes-decisionnels-pour-les-dirigeants",
    category: "dirigeant",
  },

  // Management Commercial
  {
    title: "Dispositif & Outils de Pilotage de la Performance Commerciale",
    desc: "Plus de 50 outils, matrices, plans pour modéliser, planifier et orchestrer plus aisément la performance commerciale.",
    price: "$37",
    rating: 4.6,
    reviews: 645,
    img: "/cours/dispositif-pilotage-commercial.jpg",
    badge: "Bestseller",
    type: "Cours",
    href: "/cours/dispositif-outils-de-pilotage-commercial",
    category: "management-commercial-4-0",
  },
  {
    title: "Réussir son Management Commercial",
    desc: "État d'Esprit, Dispositifs et méthodes de pilotage commercial pour les directeurs et managers commerciaux.",
    price: "$59",
    rating: 4.7,
    reviews: 389,
    img: "/cours/reussir-management-commercial.jpg",
    badge: "Top noté",
    type: "Cours",
    href: "/cours/reussir-son-management-commercial",
    category: "management-commercial-4-0",
  },
  {
    title: "L'Art de Casser la Baraque pour les Commerciaux",
    desc: "Mindset, optimisation mentale et approche inédite pour intégrer la nouvelle psychologie de la vente.",
    price: "$27",
    rating: 4.5,
    reviews: 712,
    img: "/cours/art-casser-baraque-commerciaux.png",
    badge: "Bestseller",
    type: "Cours",
    href: "/cours/lart-de-casser-la-baraque-pour-les-commerciaux",
    category: "management-commercial-4-0",
  },
  {
    title: "Réussir le Job de Manager Commercial",
    desc: "Développez un véritable état d'esprit marketing et adoptez les rôles, engagements et réflexes d'un manager commercial audacieux pour occuper le terrain.",
    price: "$27",
    rating: 4.6,
    reviews: 298,
    img: "/cours/reussir-job-manager-commercial.jpg",
    type: "Cours",
    href: "/cours/reussir-le-job-de-manager-commercial",
    category: "management-commercial-4-0",
  },

  // Parcours d'Élite
  {
    title: "Parcours Dirigeant d'Élite",
    desc: "L'itinéraire d'excellence pour les dirigeants ambitieux : stratégie, leadership, impact. Tout ce qu'il faut pour exceller au sommet.",
    price: "$249",
    rating: 4.9,
    reviews: 210,
    img: "/cat-dirigeant.png",
    badge: "Élite",
    type: "Parcours",
    href: "/cours/parcours-dirigeant-delite",
    category: "parcours",
  },
  {
    title: "Parcours IA & Performance Professionnelle d'Élite",
    desc: "Maîtrisez l'IA et boostez votre performance professionnelle avec ce parcours élite couvrant tous les outils et méthodes IA essentiels.",
    price: "$99",
    rating: 4.8,
    reviews: 185,
    img: "/cat-intelligence-artificielle.jpg",
    badge: "Élite",
    type: "Parcours",
    href: "/cours/parcours-ia-performance-professionnelle-delite",
    category: "parcours",
  },
  {
    title: "Parcours Manager d'Élite",
    desc: "Devenez un manager d'élite avec ce parcours complet couvrant toutes les dimensions du management moderne : équipe, performance, communication et leadership.",
    price: "$79",
    rating: 4.8,
    reviews: 172,
    img: "/cat-management-capital-humain.png",
    badge: "Élite",
    type: "Parcours",
    href: "/cours/parcours-manager-delite",
    category: "parcours",
  },
  {
    title: "Parcours Manager Commercial d'Élite",
    desc: "Parcours complet pour exceller dans le management commercial à l'ère digitale : pipeline, coaching commercial, pilotage et performance.",
    price: "$79",
    rating: 4.8,
    reviews: 164,
    img: "/cat-management-commercial.png",
    badge: "Élite",
    type: "Parcours",
    href: "/cours/parcours-manager-commercial-delite",
    category: "parcours",
  },
  {
    title: "Parcours RH & Capital Humain d'Élite",
    desc: "Maîtrisez les enjeux RH modernes et devenez un expert du capital humain : acquisition, engagement, développement et fidélisation des talents.",
    price: "$79",
    rating: 4.8,
    reviews: 148,
    img: "/cours/parcours-rh-capital-humain-elite.jpg",
    badge: "Élite",
    type: "Parcours",
    href: "/cours/parcours-rh-capital-humain-delite",
    category: "parcours",
  },
  {
    title: "Parcours Clarté & Performance Personnelle d'Élite",
    desc: "Gagnez en clarté, organisation et performance personnelle avec ce parcours holistique couvrant gestion du temps, objectifs et résilience.",
    price: "$59",
    rating: 4.8,
    reviews: 132,
    img: "/cat-developpement-personnel.png",
    badge: "Élite",
    type: "Parcours",
    href: "/cours/parcours-clarte-performance-personnelle-delite",
    category: "parcours",
  },
  {
    title: "Parcours Chef de Service 5.0",
    desc: "Le parcours complet pour passer d'expert nommé manager à chef de service que tout le monde respecte, qui délivre sans relance et dont l'équipe produit l'excellence opérationnelle.",
    price: "$97",
    rating: 4.8,
    reviews: 142,
    img: "/cours/parcours-chef-de-service-5-0.jpg",
    badge: "Premium",
    type: "Parcours",
    href: "/cours/parcours-chef-de-service-5-0",
    category: "parcours",
  },

  // Management d'Équipe — Parcours Sanity (images fournies via fallback)
  {
    title: "Parcours Manager d'Équipe 4.0 VVIP",
    desc: "Le parcours VVIP le plus complet pour maîtriser toutes les dimensions du management d'équipe 4.0 : leadership, performance, coaching et transformation.",
    price: "$453",
    rating: 4.9,
    reviews: 124,
    img: "https://shop.managersity.com/wp-content/uploads/2025/07/IMAGE__1_-1.png",
    badge: "VVIP",
    type: "Parcours",
    href: "/cours/parcours-manager-dequipe-4-0-vvip",
    category: "parcours",
  },
  {
    title: "Parcours Manager d'Équipe 4.0 VVIP — 3 tranches",
    desc: "Le parcours VVIP Manager d'Équipe 4.0, payable en 3 tranches pour faciliter votre investissement.",
    price: "$179",
    rating: 4.9,
    reviews: 68,
    img: "/cours/parcours-manager-equipe-vvip-3-tranches.jpg",
    badge: "VVIP",
    type: "Parcours",
    href: "/cours/parcours-manager-dequipe-4-0-vvip-3-tranches",
    category: "parcours",
  },
  {
    title: "Parcours Manager d'Équipe 4.0 VIP",
    desc: "Le parcours VIP pour maîtriser les fondamentaux du management d'équipe 4.0 et monter en puissance.",
    price: "$197",
    rating: 4.8,
    reviews: 96,
    img: "/cours/parcours-manager-equipe-vip.jpg",
    badge: "VIP",
    type: "Parcours",
    href: "/cours/parcours-manager-dequipe-4-0-vip",
    category: "parcours",
  },
  {
    title: "Parcours Middle Manager 4.0",
    desc: "Le parcours dédié aux Middle Managers pour développer leur impact stratégique et opérationnel.",
    price: "$297",
    rating: 4.8,
    reviews: 78,
    img: "https://shop.managersity.com/wp-content/uploads/2025/02/PARCOURS-MIDDLE-MANAGERS-4.0.png",
    type: "Parcours",
    href: "/cours/parcours-middle-manager-4-0",
    category: "management-d-equipe",
  },

  // Management d'Équipe
  {
    title: "Le Coaching Managérial 4.0",
    desc: "Maitriser et utiliser la méthodologie pour coacher efficacement un collaborateur (ses collaborateurs) et tirer le meilleur parti…",
    price: "$29.90",
    rating: 4.6,
    reviews: 487,
    img: "/cours/coaching-managerial.jpg",
    type: "Cours",
    href: "/cours/le-coaching-managerial-4-0",
    category: "management-d-equipe",
  },
  {
    title: "Bâtir une Équipe Performante",
    desc: "Approches, méthodes, état d'esprit et mécanismes inédits et éprouvés pour bâtir une équipe solide, complémentaire et…",
    price: "$29.90",
    rating: 4.7,
    reviews: 523,
    img: "/cours/batir-equipe-performante",
    type: "Cours",
    href: "/cours/batir-une-equipe-performante",
    category: "management-d-equipe",
  },
  {
    title: "Optimiser sa Posture Managériale",
    desc: "Sortir de la naiveté, comprendre les règles d'excellence et l'élévation managériale et affirmer sa maturité structurelle et…",
    price: "$27",
    rating: 4.5,
    reviews: 389,
    img: "/cours/optimiser-posture-manageriale.jpg",
    type: "Cours",
    href: "/cours/optimiser-sa-posture-manageriale",
    category: "management-d-equipe",
  },
  {
    title: "L'Art de Catalyser et Piloter la Performance",
    desc: "Outils et méthodes pour scénariser, catalyser et orchestrer la performance au day-to-day dans un contexte managérial exigeant.",
    price: "$59",
    rating: 4.7,
    reviews: 412,
    img: "/cours/catalyser-piloter-performance.jpg",
    badge: "Premium",
    type: "Cours",
    href: "/cours/lart-de-catalyser-et-piloter-la-performance",
    category: "management-d-equipe",
  },
  {
    title: "Leadership & Le Pouvoir de l'Influence au 21è Siècle",
    desc: "Développez un leadership authentique et maîtrisez l'art d'influencer sans autorité formelle pour mobiliser vos équipes et partenaires.",
    price: "$47",
    rating: 4.6,
    reviews: 324,
    img: "/cours/leadership-situationnel.png",
    type: "Cours",
    href: "/cours/leadership-pouvoir-de-linfluence",
    category: "management-d-equipe",
  },

  // Management du Capital Humain
  {
    title: "Management Stratégique du Capital Humain",
    desc: "Comment s'assurer d'avoir des Hommes & Femmes de qualité, en quantité et bien formés et bien outillés, engagés, heureux…",
    price: "$47",
    rating: 4.6,
    reviews: 412,
    img: "/cours/management-strategique-capital-humain.png",
    type: "Cours",
    href: "/cours/management-strategique-du-capital-humain",
    category: "management-du-capital-humain",
  },

  // Développement Personnel
  {
    title: "Piloter sa Résilience et son Bien-être Personnel",
    desc: "État d'esprit et mécanismes inédits pour trouver son épanouissement et rester fort dans un monde en tension.",
    price: "$27",
    rating: 4.6,
    reviews: 523,
    img: "/cours/piloter-resilience.png",
    type: "Cours",
    href: "/cours/piloter-sa-resilience-et-son-bien-etre-personnel",
    category: "developpement-personnel",
  },
  {
    title: "Gestion du Stress : Méthodes Inédites pour Anticiper les Pressions et les Gérer",
    desc: "Méthodes inédites d'organisation pour prévenir et gérer intelligemment les moments de stress.",
    price: "$27",
    rating: 4.7,
    reviews: 841,
    img: "/cours/gestion-stress.jpg",
    badge: "Bestseller",
    type: "Cours",
    href: "/cours/gestion-du-stress-et-des-pressions",
    category: "developpement-personnel",
  },
  {
    title: "Développer son Potentiel et se Mettre à la Dimension de ses Rêves",
    desc: "Prendre en main sa vie et sa carrière, prendre conscience de son potentiel et réaliser la meilleure version de soi-même.",
    price: "$27",
    rating: 4.8,
    reviews: 1200,
    img: "/cours/developper-potentiel.png",
    badge: "Top noté",
    type: "Cours",
    href: "/cours/developper-son-potentiel-et-se-mettre-a-la-dimension-de-ses-reves",
    category: "developpement-personnel",
  },
  {
    title: "Intelligence Émotionnelle & Gestion des Relations avec les Autres",
    desc: "Travailler son self-management, devenir confiant et autodéterminé, maîtriser ses émotions.",
    price: "$27",
    rating: 4.6,
    reviews: 654,
    img: "/cours/intelligence-emotionnelle.png",
    type: "Cours",
    href: "/cours/intelligence-emotionnelle-gestion-des-relations-avec-les-autres",
    category: "developpement-personnel",
  },
  {
    title: "Méthodes de Gestion du Temps & de Discipline Personnelles pour les Pros",
    desc: "Méthodes simples et inédites pour tirer le meilleur parti de ses journées et délivrer des performances records.",
    price: "$59",
    rating: 4.7,
    reviews: 912,
    img: "/cours/gestion-temps-discipline.png",
    badge: "Bestseller",
    type: "Cours",
    href: "/cours/methodes-de-gestion-du-temps-dorganisation-et-de-discipline-personnelle-pour-les-pros",
    category: "developpement-personnel",
  },
  {
    title: "L'Art de se Fixer les Objectifs et les Atteindre",
    desc: "L'état d'esprit et la méthodologie avec des outils pratiques pour vous fixer n'importe quel type d'objectif.",
    price: "$27",
    rating: 4.5,
    reviews: 478,
    img: "/cours/art-fixer-objectifs.png",
    type: "Cours",
    href: "/cours/lart-de-se-fixer-les-objectifs-les-atteindre-et-les-atteindre",
    category: "developpement-personnel",
  },

  // Entrepreneuriat
  {
    title: "Structurer et Piloter une Vision d'Entreprise",
    desc: "L'art de devenir un visionnaire ou comment faire une incursion dans le futur, projecter le développement d'une entreprise et…",
    price: "$47",
    rating: 4.6,
    reviews: 356,
    img: "/cours/structurer-piloter-vision.jpg",
    type: "Cours",
    href: "/cours/structurer-et-piloter-une-vision-dentreprise",
    category: "entrepreneuriat",
  },
  {
    title: "État d'Esprit & Résilience Entrepreneuriale",
    desc: "État d'esprit, approches inédites et postures adéquates pour porter plus sereinement les enjeux liés à l'aventure…",
    price: "$27",
    rating: 4.5,
    reviews: 412,
    img: "/cours/etat-esprit-resilience.png",
    type: "Cours",
    href: "/cours/etat-desprit-resilience-entrepreneuriale",
    category: "entrepreneuriat",
  },

  // Note : les cours Vendeur Elite (L'Art de Casser la Baraque, Dispositif & Outils
  // de Pilotage) sont stockes une seule fois en categorie management-commercial-4-0
  // et apparaissent aussi dans Vendeur Elite Expert 4.0 via une regle de filtre.

];

export type CategoryMeta = {
  label: string;
  slug: string;
  description: string;
  icon: string;
  color: string;
};

export const categoryMeta: Record<string, CategoryMeta> = {
  "intelligence-artificielle": {
    label: "Intelligence Artificielle",
    slug: "intelligence-artificielle",
    description: "Maîtrisez l'IA et ses applications pour booster votre productivité et celle de votre organisation.",
    icon: "🤖",
    color: "from-indigo-600 to-violet-400",
  },
  "transformation-digitale-4-0": {
    label: "Transformation Digitale 4.0",
    slug: "transformation-digitale-4-0",
    description: "Maîtrisez la digitalisation pour transformer votre organisation et votre carrière.",
    icon: "⚡",
    color: "from-cyan-600 to-sky-400",
  },
  dirigeant: {
    label: "Dirigeant",
    slug: "dirigeant",
    description: "Développez votre excellence en tant que dirigeant et prenez votre organisation à un niveau supérieur.",
    icon: "👑",
    color: "from-violet-600 to-purple-400",
  },
  "management-commercial-4-0": {
    label: "Management Commercial 4.0",
    slug: "management-commercial-4-0",
    description: "Pilotez votre performance commerciale avec les meilleures méthodes et outils du marché.",
    icon: "📈",
    color: "from-blue-600 to-blue-400",
  },
  "management-d-equipe": {
    label: "Management d'Équipe",
    slug: "management-d-equipe",
    description: "Renforcez votre leadership et animez vos équipes pour atteindre l'excellence opérationnelle.",
    icon: "👥",
    color: "from-teal-600 to-teal-400",
  },
  "management-du-capital-humain": {
    label: "Management du Capital Humain",
    slug: "management-du-capital-humain",
    description: "Optimisez la gestion des talents, la culture et le développement de vos ressources humaines.",
    icon: "🤝",
    color: "from-rose-600 to-pink-400",
  },
  "developpement-personnel": {
    label: "Développement Personnel",
    slug: "developpement-personnel",
    description: "Libérez votre potentiel, gérez vos émotions et construisez une vie professionnelle épanouissante.",
    icon: "🌱",
    color: "from-green-600 to-emerald-400",
  },
  entrepreneuriat: {
    label: "Entrepreneuriat",
    slug: "entrepreneuriat",
    description: "Structurez et faites croître votre entreprise avec les meilleures stratégies et outils.",
    icon: "🚀",
    color: "from-orange-500 to-amber-500",
  },
  "vendeur-elite-expert-4-0": {
    label: "Vendeur Elite Expert 4.0",
    slug: "vendeur-elite-expert-4-0",
    description: "Maîtrisez les techniques de vente avancées pour dépasser vos objectifs commerciaux.",
    icon: "🏆",
    color: "from-yellow-600 to-amber-400",
  },
  parcours: {
    label: "Parcours",
    slug: "parcours",
    description: "Les parcours complets et certifiants Managersity pour maîtriser de bout en bout une spécialité managériale.",
    icon: "🎖️",
    color: "from-amber-600 to-yellow-400",
  },
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Extrait le slug depuis l'URL href d'un cours */
export function getCourseSlug(course: Course): string {
  return course.href.split("/").pop() || "";
}

/** Trouve un cours par son slug */
export function getCourseBySlug(slug: string): Course | null {
  return allCourses.find((c) => c.href.split("/").pop() === slug) || null;
}

/** Retourne tous les slugs (pour generateStaticParams) */
export function getAllCourseSlugs(): string[] {
  return [...new Set(allCourses.map((c) => c.href.split("/").pop() || "").filter(Boolean))];
}

/** Points d'apprentissage génériques par catégorie */
export const learnPoints: Record<string, string[]> = {
  "intelligence-artificielle": [
    "Comprendre l'IA de A à Z et ses applications concrètes",
    "Automatiser les tâches répétitives pour gagner en productivité",
    "Utiliser la DATA pour prendre de meilleures décisions",
    "Intégrer les outils IA dans votre workflow quotidien",
    "Rester compétitif dans un environnement digitalisé",
    "Booster vos performances avec des outils No-Code & IA",
  ],
  "transformation-digitale-4-0": [
    "Comprendre les enjeux business de la transformation digitale",
    "Définir une méthodologie de transformation adaptée",
    "Optimiser l'excellence opérationnelle par le digital",
    "Piloter un projet de transformation digitale",
    "Aligner la stratégie digitale avec les objectifs business",
    "Maîtriser les outils et frameworks de la transformation",
  ],
  dirigeant: [
    "Développer votre vision stratégique et votre densité managériale",
    "Prendre des décisions complexes avec méthode et assurance",
    "Gérer vos parties prenantes avec intelligence diplomatique",
    "Structurer et transformer votre organisation durablement",
    "Développer votre leadership situationnel",
    "Rayonner en tant que dirigeant 5.0 en Afrique",
  ],
  "management-commercial-4-0": [
    "Piloter votre équipe commerciale avec efficacité",
    "Utiliser les bons outils et matrices de performance commerciale",
    "Définir et atteindre vos objectifs de vente",
    "Motiver et coacher vos commerciaux au quotidien",
    "Analyser et optimiser vos performances business",
    "Maîtriser le management commercial 4.0",
  ],
  "management-d-equipe": [
    "Développer un leadership inspirant et situationnel",
    "Motiver et fédérer vos équipes autour d'un objectif commun",
    "Gérer les conflits avec méthode et sérénité",
    "Piloter la performance quotidienne de vos collaborateurs",
    "Conduire le changement organisationnel avec succès",
    "Créer une culture de l'excellence et de la responsabilisation",
  ],
  "management-du-capital-humain": [
    "Attirer, recruter et fidéliser les meilleurs talents",
    "Concevoir et déployer une stratégie RH performante",
    "Maîtriser l'IA appliquée aux ressources humaines",
    "Développer les compétences de vos collaborateurs",
    "Construire une culture d'entreprise forte et engageante",
    "Optimiser la gestion des carrières et la mobilité interne",
  ],
  "developpement-personnel": [
    "Renforcer votre résilience et piloter votre bien-être",
    "Maîtriser la gestion du stress et des pressions",
    "Développer votre intelligence émotionnelle",
    "Optimiser votre gestion du temps et de votre énergie",
    "Vous fixer des objectifs ambitieux et les atteindre",
    "Libérer votre plein potentiel personnel et professionnel",
  ],
  entrepreneuriat: [
    "Concevoir et valider votre modèle d'affaires",
    "Structurer et faire croître votre entreprise",
    "Maîtriser l'art de la stratégie et de la disruption marché",
    "Lever des fonds et gérer votre trésorerie",
    "Construire et piloter une organisation performante",
    "Développer un réseau solide et des partenariats stratégiques",
  ],
  "vendeur-elite-expert-4-0": [
    "Intégrer la nouvelle psychologie de la vente",
    "Maîtriser les techniques de prospection et de closing",
    "Gérer les objections avec confiance et efficacité",
    "Construire des relations durables avec vos clients",
    "Utiliser les outils digitaux pour booster vos ventes",
    "Dépasser vos quotas et exceller dans votre métier",
  ],
  parcours: [
    "Suivre un parcours structuré, progressif et certifiant",
    "Maîtriser toutes les compétences clés d'une spécialité managériale",
    "Bénéficier d'un accompagnement complet sur plusieurs modules",
    "Obtenir une certification reconnue à la fin du parcours",
    "Accéder à des outils, modèles et ressources premium",
    "Accélérer votre montée en puissance professionnelle",
  ],
};
