export type CourseDetail = {
  slug: string;
  title: string;
  category: string;
  price: number;
  originalPrice?: number;
  shopUrl: string;
  enrollUrl?: string;
  tagline: string;
  totalChapters?: number;
  totalLessons?: number;
  learns?: string[];
  chapters?: string[];
  benefits?: { title: string; desc: string }[];
};

export const COURSES: CourseDetail[] = [

  // ── INTELLIGENCE ARTIFICIELLE ─────────────────────────────────────────────

  {
    slug: "ia-pour-les-managers",
    title: "Intelligence Artificielle pour les Managers",
    category: "Intelligence Artificielle",
    price: 59000,
    originalPrice: 197000,
    shopUrl: "https://shop.managersity.com/produit/ia-pour-les-managers/",
    enrollUrl: "https://www.managersity.co/enroll/3468759",
    tagline: "Comprendre l'IA de A-Z avec une immersion concrète dans les utilisations pratiques pour booster la productivité et les performances de votre équipe.",
    totalChapters: 3,
    totalLessons: 39,
    learns: [
      "Utiliser des outils d'IA (ChatGPT, Copilot, Notion AI…) pour rédiger, synthétiser et analyser",
      "Gagner du temps sur les réunions, comptes-rendus, mails et feedbacks",
      "Automatiser des tâches clés (RH, planning, reporting…)",
      "Créer un agent IA sans coder pour vous assister au quotidien",
      "Coacher vos équipes dans un contexte hybride (humains + IA)",
      "Adopter une posture de leadership augmenté par l'IA",
    ],
    chapters: [
      "Introduction : Comprendre l'IA pour les managers (origine, écosystème, applications)",
      "Partie 1 : De l'essoufflement managérial à l'optimisation managériale augmentée par l'IA",
      "Partie 2 : Manager efficacement son équipe à l'ère de l'IA",
    ],
    benefits: [
      {
        title: "Comprendre l'IA sans être tech",
        desc: "Pas besoin d'être ingénieur pour comprendre et utiliser l'intelligence artificielle. La formation vous explique, en termes simples, comment fonctionne l'IA et comment l'appliquer dans votre rôle de manager.",
      },
      {
        title: "L'IA au service du quotidien managérial",
        desc: "L'IA va vous aider à automatiser vos tâches répétitives, mieux organiser vos réunions, rédiger vos comptes-rendus et suivre les performances de votre équipe avec moins d'effort.",
      },
      {
        title: "Devenir un leader augmenté avec l'IA",
        desc: "L'IA ne remplace pas le manager, elle le renforce. En l'utilisant comme un copilote, vous développez une posture de leadership plus stratégique, plus réactive et plus humaine.",
      },
    ],
  },

  {
    slug: "ia-pour-sales-managers-5-0-le-cours-complet",
    title: "L'IA pour les Managers Commerciaux 5.0 : Le Cours Complet",
    category: "Intelligence Artificielle",
    price: 59000,
    originalPrice: 197000,
    shopUrl: "https://shop.managersity.com/produit/ia-pour-sales-managers-5-0-le-cours-complet/",
    enrollUrl: "https://www.managersity.co/enroll/3500554",
    tagline: "Comment les managers commerciaux innovants utilisent la DATA, l'IA et la Technologie pour avoir plusieurs coups d'avance sur leurs concurrents.",
    totalChapters: 5,
    totalLessons: 39,
    learns: [
      "Utiliser des outils d'IA (ChatGPT, Power BI Intelligence, Tableau AI…) pour analyser, décider et communiquer",
      "Automatiser le reporting, l'analyse de performance commerciale et la veille concurrentielle",
      "Créer des dashboards prédictifs sans coder pour piloter votre performance en temps réel",
      "Anticiper les tendances marché, optimiser les choix et le coaching des commerciaux",
      "Transformer votre pilotage commercial et accompagner vos équipes dans l'adoption de l'IA",
      "Adopter une posture de leader commercial disruptif augmenté par l'IA",
    ],
    chapters: [
      "Introduction : L'IA ne va pas remplacer les commerciaux mais les managers qui pilotent à l'ancienne",
      "Partie 1 : Intelligence artificielle, DATA et pilotage de la performance commerciale",
      "Partie 2 : Immersion dans l'univers IA — ce que le manager commercial doit savoir",
      "Partie 3 : De l'essoufflement à l'optimisation de l'excellence managériale commerciale",
      "Partie 4 : Implémenter et intégrer l'IA à son management commercial de A à Z",
    ],
    benefits: [
      {
        title: "Automatiser les tâches répétitives et libérer du temps stratégique",
        desc: "Apprenez à utiliser l'IA comme levier de croissance accessible, rentable et différenciant pour dépasser vos concurrents et réaliser vos quotas bien plus vite.",
      },
      {
        title: "Optimiser le pilotage commercial en temps réel",
        desc: "L'IA transforme votre pilotage : anticiper les tendances marché, optimiser votre chaîne de valeur, personnaliser l'expérience client et accélérer vos prises de décision.",
      },
      {
        title: "Personnaliser et automatiser le coaching commercial",
        desc: "En utilisant l'IA comme copilote intelligent, vous développez un leadership plus anticipatif, plus agile et plus innovant face aux défis commerciaux.",
      },
    ],
  },

  {
    slug: "ia-pour-les-professionnels",
    title: "IA pour Assistants & Professionnels : Le Cours Complet",
    category: "Intelligence Artificielle",
    price: 29000,
    originalPrice: 97000,
    shopUrl: "https://shop.managersity.com/produit/ia-pour-les-professionnels/",
    enrollUrl: "https://www.managersity.co/enroll/3499319",
    tagline: "Comment les professionnels qui maîtrisent l'IA produisent en 2 heures ce qui prend 2 jours à leurs collègues. L'IA devient votre copilote.",
    totalChapters: 1,
    totalLessons: 5,
    learns: [
      "Utiliser les outils d'IA (ChatGPT, Claude, Gemini, Copilot, Perplexity) pour rédiger, analyser et décider 3x plus vite",
      "Écrire des prompts structurés avec le framework RCTCF pour obtenir des résultats exploitables du premier coup",
      "Appliquer l'IA à votre métier spécifique avec des cas d'usage concrets (finance, commercial, RH, juridique)",
      "Créer vos propres assistants IA permanents qui connaissent votre entreprise et travaillent pour vous 24h/24",
      "Classer vos tâches avec le framework SCRA pour identifier où l'IA vous fait gagner le plus de temps",
      "Déployer l'IA dans votre équipe avec un plan de 90 jours concret et mesurable",
    ],
    chapters: [
      "Module 1 : L'IA offre une opportunité historique à tous les professionnels",
    ],
    benefits: [
      {
        title: "Comprendre l'IA sans être tech",
        desc: "Pas besoin d'être ingénieur pour transformer votre façon de travailler. La formation vous explique l'IA en termes simples et vous montre comment l'appliquer concrètement dès demain.",
      },
      {
        title: "Maîtriser l'art du prompt et créer vos assistants IA permanents",
        desc: "Découvrez le framework RCTCF pour obtenir des résultats excellents du premier coup, et créez vos propres assistants IA qui travaillent pour vous 24h/24.",
      },
      {
        title: "Déployer l'IA dans votre équipe et votre organisation",
        desc: "Apprenez à chiffrer le ROI, à accompagner vos équipes dans l'adoption de l'IA et à mettre en place une gouvernance responsable avec un plan de 90 jours.",
      },
    ],
  },

  {
    slug: "ia-pour-les-rh",
    title: "IA pour Manager RH 5.0 : Le Cours Complet",
    category: "Intelligence Artificielle",
    price: 59000,
    originalPrice: 197000,
    shopUrl: "https://shop.managersity.com/produit/ia-pour-les-rh/",
    enrollUrl: "https://www.managersity.co/enroll/3499149",
    tagline: "Transformez vos RH à l'ère de l'IA. Sourcing automatisé, prédiction des départs, onboarding personnalisé : l'IA devient votre copilote RH.",
    totalChapters: 4,
    totalLessons: 39,
    learns: [
      "Utiliser des outils d'IA (ChatGPT, LinkedIn Talent Insights, HiBob AI…) pour recruter, évaluer et communiquer",
      "Automatiser le sourcing, la sélection CV, les entretiens et l'onboarding collaborateur",
      "Créer des chatbots RH sans coder pour répondre aux questions des collaborateurs",
      "Analyser l'engagement, prédire les départs et optimiser la rétention des talents",
      "Personnaliser les parcours de formation et de développement des compétences",
      "Adopter une posture de RH Business Partner augmenté par l'IA",
    ],
    chapters: [
      "Introduction : L'IA et la DATA sont une opportunité pour les opérations RH répétitives et la stratégie",
      "Partie 1 : Comprendre l'IA pour les managers (origine, écosystème, applications)",
      "Partie 2 : De l'essoufflement managérial à l'optimisation managériale augmentée par l'IA",
      "Partie 3 : Manager efficacement son équipe RH à l'ère de l'IA",
    ],
    benefits: [
      {
        title: "Comprendre l'IA sans être data scientist",
        desc: "Pas besoin d'être tech pour révolutionner vos RH. La formation vous explique l'IA en termes simples, avec des applications concrètes dans l'univers RH.",
      },
      {
        title: "L'IA au service du quotidien RH",
        desc: "L'IA automatise le sourcing candidats, personnalise les parcours d'onboarding, analyse l'engagement des équipes et optimise vos processus d'évaluation.",
      },
      {
        title: "Devenir un RH leader augmenté avec l'IA",
        desc: "L'IA ne remplace pas le RH, elle le renforce. Développez une approche RH plus stratégique, plus prédictive et plus humaine pour anticiper les besoins de vos talents.",
      },
    ],
  },

  {
    slug: "kit-du-manager-augmente-ia",
    title: "Kit du Manager Augmenté IA",
    category: "Intelligence Artificielle",
    price: 39000,
    originalPrice: 199000,
    shopUrl: "https://shop.managersity.com/produit/kit-du-manager-augmente-ia/",
    tagline: "Boîte à outils complète pour le manager moderne : templates, prompts et guides pratiques pour utiliser l'IA efficacement au quotidien.",
  },

  {
    slug: "lia-pour-les-dirigeants-5-0-le-cours-complet",
    title: "L'IA pour les DG et les Dirigeants 5.0 : Le Cours Complet",
    category: "Intelligence Artificielle",
    price: 97000,
    originalPrice: 297000,
    shopUrl: "https://shop.managersity.com/produit/lia-pour-les-dirigeants-5-0-le-cours-complet/",
    enrollUrl: "https://www.managersity.co/enroll/3499006",
    tagline: "Comment les DG et dirigeants 5.0 utilisent l'IA pour optimiser le cadrage stratégique, la planification et le pilotage de leurs organisations.",
    totalChapters: 4,
    totalLessons: 58,
    learns: [
      "Utiliser ChatGPT, Power BI Intelligence et Tableau AI pour analyser, décider et communiquer",
      "Automatiser le reporting, l'analyse financière, la veille concurrentielle et la planification stratégique",
      "Créer des dashboards prédictifs sans coder pour piloter la performance en temps réel",
      "Anticiper les tendances marché, optimiser les coûts et identifier de nouvelles opportunités de croissance",
      "Transformer l'organisation et accompagner les équipes dans l'adoption de l'IA",
      "Adopter une posture de leader disruptif augmenté par l'IA",
    ],
    chapters: [
      "Introduction : L'IA appliquée au management — la meilleure opportunité d'excellence managériale",
      "Partie 1 : Immersion dans l'univers IA — ce que le dirigeant doit savoir et retenir",
      "Partie 2 : L'excellence dirigeant optimisée IA",
      "Partie 3 : L'entreprise augmentée — comment créer les conditions pour tirer le meilleur parti de l'IA",
    ],
    benefits: [
      {
        title: "Comprendre l'IA sans être tech",
        desc: "Pas besoin d'être ingénieur pour révolutionner votre entreprise. La formation vous explique l'IA en termes business et comment l'intégrer stratégiquement dans votre organisation.",
      },
      {
        title: "L'IA au service du leadership stratégique",
        desc: "L'IA transforme le pilotage : anticiper les tendances marché, optimiser la chaîne de valeur, personnaliser l'expérience client et accélérer les prises de décision.",
      },
      {
        title: "Devenir un dirigeant visionnaire augmenté par l'IA",
        desc: "L'IA ne remplace pas le DG, elle amplifie sa vision. Développez un leadership plus anticipatif, plus agile et plus innovant pour guider votre organisation vers les opportunités de demain.",
      },
    ],
  },

  // ── PACKS PHARES ──────────────────────────────────────────────────────────

  {
    slug: "parcours-dirigeant",
    title: "Parcours Dirigeant Certifié",
    category: "Packs Phares",
    price: 304900,
    originalPrice: 597000,
    shopUrl: "https://shop.managersity.com/produit/parcours-dirigeant/",
    tagline: "Le parcours complet et certifiant pour développer votre excellence de direction — stratégie, leadership, finance, capital humain et transformation.",
  },
  {
    slug: "parcours-dirigeant-delite",
    title: "Parcours Dirigeant d'Élite",
    category: "Packs Phares",
    price: 249000,
    shopUrl: "https://shop.managersity.com/produit/parcours-dirigeant-delite/",
    tagline: "L'itinéraire d'excellence pour les dirigeants ambitieux : stratégie, leadership, impact. Tout ce qu'il faut pour exceller au sommet.",
  },
  {
    slug: "parcours-ia-performance-professionnelle-delite",
    title: "Parcours IA & Performance Professionnelle d'Élite",
    category: "Packs Phares",
    price: 99000,
    shopUrl: "https://shop.managersity.com/produit/parcours-ia-performance-professionnelle-delite/",
    tagline: "Maîtrisez l'IA et boostez votre performance professionnelle avec ce parcours élite couvrant tous les outils et méthodes IA essentiels.",
  },
  {
    slug: "parcours-manager-delite",
    title: "Parcours Manager d'Élite",
    category: "Packs Phares",
    price: 79000,
    shopUrl: "https://shop.managersity.com/produit/parcours-manager-delite/",
    tagline: "Devenez un manager d'élite avec ce parcours complet couvrant toutes les dimensions du management moderne : équipe, performance, communication et leadership.",
  },
  {
    slug: "parcours-manager-commercial-delite",
    title: "Parcours Manager Commercial d'Élite",
    category: "Packs Phares",
    price: 79000,
    shopUrl: "https://shop.managersity.com/produit/parcours-manager-commercial-delite/",
    tagline: "Parcours complet pour exceller dans le management commercial à l'ère digitale : pipeline, coaching commercial, pilotage et performance.",
  },
  {
    slug: "parcours-rh-capital-humain-delite",
    title: "Parcours RH & Capital Humain d'Élite",
    category: "Packs Phares",
    price: 79000,
    shopUrl: "https://shop.managersity.com/produit/parcours-rh-capital-humain-delite/",
    tagline: "Maîtrisez les enjeux RH modernes et devenez un expert du capital humain : acquisition, engagement, développement et fidélisation des talents.",
  },
  {
    slug: "parcours-clarte-performance-personnelle-delite",
    title: "Parcours Clarté & Performance Personnelle d'Élite",
    category: "Packs Phares",
    price: 59000,
    shopUrl: "https://shop.managersity.com/produit/parcours-clarte-performance-personnelle-delite/",
    tagline: "Gagnez en clarté, organisation et performance personnelle avec ce parcours holistique couvrant gestion du temps, objectifs et résilience.",
  },

  // ── MANAGEMENT D'ÉQUIPE ───────────────────────────────────────────────────

  {
    slug: "parcours-manager-dequipe-4-0-vvip",
    title: "Parcours Manager d'Équipe 4.0 VVIP",
    category: "Management d'Équipe",
    price: 297000,
    originalPrice: 397000,
    shopUrl: "https://shop.managersity.com/produit/parcours-manager-dequipe-4-0-vvip/",
    tagline: "Le parcours VVIP le plus complet pour maîtriser toutes les dimensions du management d'équipe 4.0 : leadership, performance, coaching et transformation.",
  },
  {
    slug: "parcours-middle-manager-4-0",
    title: "Parcours Middle Manager 4.0",
    category: "Management d'Équipe",
    price: 127000,
    shopUrl: "https://shop.managersity.com/produit/parcours-middle-manager-4-0/",
    tagline: "Devenez un middle manager d'exception : leadership situationnel, gestion d'équipe, communication ascendante et performance opérationnelle.",
  },
  {
    slug: "parcours-manager-dequipe-4-0-vvip-3-tranches",
    title: "Parcours Manager d'Équipe 4.0 VVIP — 3 tranches",
    category: "Management d'Équipe",
    price: 120000,
    shopUrl: "https://shop.managersity.com/produit/parcours-manager-dequipe-4-0-vvip-3-tranches/",
    tagline: "Le parcours VVIP complet en 3 versements pour booster vos compétences managériales sans contrainte financière.",
  },
  {
    slug: "parcours-manager-dequipe-4-0-vip",
    title: "Parcours Manager d'Équipe 4.0 VIP",
    category: "Management d'Équipe",
    price: 97000,
    originalPrice: 159000,
    shopUrl: "https://shop.managersity.com/produit/parcours-manager-dequipe-4-0-vip/",
    tagline: "Parcours VIP pour développer toutes vos compétences de manager d'équipe à l'ère 4.0 : leadership, cohésion, performance et bien-être.",
  },

  // ── PARCOURS DIRIGEANT ────────────────────────────────────────────────────

  {
    slug: "pack-25-ebooks-pour-dirigeant",
    title: "PACK 25 EBOOKS POUR DIRIGEANT",
    category: "Parcours Dirigeant",
    price: 99000,
    originalPrice: 159000,
    shopUrl: "https://shop.managersity.com/produit/pack-25-ebooks-pour-dirigeant/",
    tagline: "25 ebooks essentiels pour les dirigeants : stratégie, leadership, finance, transformation digitale et capital humain. Une bibliothèque complète.",
  },
  {
    slug: "maturite-manageriale-enjeux-de-direction-generale",
    title: "Maturité Managériale et Enjeux de Direction Générale",
    category: "Parcours Dirigeant",
    price: 59000,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/maturite-manageriale-enjeux-de-direction-generale/",
    enrollUrl: "https://www.managersity.co/enroll/3234141",
    tagline: "Que vous visiez le poste de DG ou y soyez déjà, ce module révèle le travail d'optimisation indispensable pour exceller à la direction générale.",
    totalChapters: 4,
    totalLessons: 35,
    learns: [
      "Comprendre les enjeux réels du poste de Directeur Général et de membre de CODIR",
      "Identifier ce que les DG qui réussissent font différemment de ceux qui échouent",
      "Procéder aux optimisations nécessaires pour vous qualifier pour le poste de top dirigeant",
      "Développer la posture, le mindset et les compétences d'une excellence dirigeante",
      "Définir vos objectifs stratégiques et piloter vos enjeux avec méthode et clarté",
      "Vous différencier et créer une valeur ajoutée unique en tant que dirigeant",
    ],
    chapters: [
      "Introduction : À la dimension dirigeant ?",
      "Partie 1 : Prendre conscience des enjeux de direction générale",
      "Partie 2 : Passer à la dimension dirigeant",
      "Partie 3 : Faire la différence en tant que dirigeant",
    ],
    benefits: [
      {
        title: "Prendre conscience des enjeux de direction générale",
        desc: "Savoir ce que cela suppose d'être membre de CODIR ou DG et les enjeux à porter quand on y est. Sortir des illusions pour voir la réalité du poste.",
      },
      {
        title: "S'élever à la dimension dirigeant",
        desc: "Procéder aux optimisations et ajustements nécessaires pour se qualifier pour le poste de Top Manager et réussir en tant que Directeur Général.",
      },
      {
        title: "S'organiser pour piloter les enjeux stratégiques",
        desc: "Définir des objectifs clairs, prioriser vos tâches par urgence et déléguer les responsabilités de manière appropriée pour maximiser votre impact.",
      },
    ],
  },
  {
    slug: "design-organisationnel-transformation-dentreprise",
    title: "Design Organisationnel & Transformation d'Entreprise",
    category: "Parcours Dirigeant",
    price: 57000,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/design-organisationnel-transformation-dentreprise/",
    enrollUrl: "https://www.managersity.co/enroll/3248526",
    tagline: "Maîtrisez la méthodologie pour diagnostiquer une organisation, évaluer ses capacités et déployer sa transformation avec succès.",
    totalChapters: 3,
    totalLessons: 30,
    learns: [
      "Diagnostiquer une organisation et identifier les leviers de performance",
      "Mettre en place l'organisation adéquate pour atteindre les performances attendues",
      "Structurer et piloter la recapacitation organisationnelle",
      "Réussir l'alignement stratégique et organisationnel",
      "Traduire une vision en un projet d'entreprise avec des optimisations concrètes",
      "Maîtriser les 6 capacités transformatives clés pour réussir la montée en régime",
    ],
    chapters: [
      "Intro : Lorsque votre organisation n'est pas calibrée pour vous permettre d'atteindre vos objectifs",
      "Partie 1 : Mettre en place l'organisation adéquate pour atteindre la performance humaine",
      "Partie 2 : Structurer et piloter la recapacitation organisationnelle",
    ],
    benefits: [
      {
        title: "Réussir le diagnostic organisationnel",
        desc: "Sachez sur quoi agir pour transformer une organisation et l'aligner sur de nouvelles perspectives de performance, de croissance et d'excellence.",
      },
      {
        title: "Réussir l'alignement organisationnel",
        desc: "Permettez à votre organisation d'assurer la montée en dimension requise pour devenir l'écosystème de réalisation parfaite de vos objectifs stratégiques.",
      },
      {
        title: "Réussir le changement organisationnel",
        desc: "Découvrez comment réussir la transformation culturelle et la mobilisation des équipes autour des changements organisationnels et le pilotage d'une vision.",
      },
    ],
  },
  {
    slug: "intelligence-emotionnelle-mecanismes-decisionnels-pour-les-dirigeants",
    title: "Jeu Intérieur du Leadership, Intelligence Émotionnelle & Mécanismes Décisionnels pour les Dirigeants",
    category: "Parcours Dirigeant",
    price: 34900,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/intelligence-emotionnelle-mecanismes-decisionnels-pour-les-dirigeants/",
    enrollUrl: "https://www.managersity.co/enroll/3239697",
    tagline: "Pour les dirigeants sous tension : méthodes inédites de leadership intérieur, d'intelligence émotionnelle et de processing pour penser, agir et décider correctement sous pression.",
    totalChapters: 4,
    totalLessons: 48,
    learns: [
      "Adopter une attitude supérieure face aux situations complexes",
      "Tenir face aux tensions constantes et rester focus résultats",
      "Opérer des choix critiques avec lucidité sous pression",
      "Maîtriser les mécanismes décisionnels des grands leaders",
      "Développer le jeu intérieur du leadership pour rester maître de la situation",
      "Gérer les émotions et éviter qu'elles ne parasitent vos décisions",
    ],
    chapters: [
      "Intro : Le vrai test de leadership",
      "Partie #1 : Reprendre le contrôle du jeu",
      "Partie #2 : L'art du processing pour gérer les situations sans émotion",
      "Partie #3 : Choix complexes & mécanismes décisionnels",
    ],
    benefits: [
      {
        title: "Rester maître de la situation",
        desc: "Même quand tout le monde perd la tête, développez la capacité à rester serein, à opérer les bonnes analyses et à orienter constamment vos équipes vers les résultats.",
      },
      {
        title: "Méthodes inédites d'intelligence émotionnelle",
        desc: "Accédez à des méthodes d'IE comme vous n'en avez jamais vues — celles que les grands leaders utilisent pour traverser les défis et en sortir plus forts.",
      },
      {
        title: "Décider et agir sereinement",
        desc: "Structurez votre processus décisionnel pour prendre les bons arbitrages et assumer pleinement les résultats, même dans les contextes les plus incertains.",
      },
    ],
  },
  {
    slug: "management-de-projet-et-realisation-des-objectifs-strategiques",
    title: "Management de Projet & Réalisation des Objectifs Stratégiques",
    category: "Parcours Dirigeant",
    price: 29000,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/management-de-projet-et-realisation-des-objectifs-strategiques/",
    enrollUrl: "https://www.managersity.co/enroll/3239721",
    tagline: "Pilotez vos projets stratégiques avec méthode et faites de l'atteinte des objectifs un processus structuré et reproductible.",
    totalChapters: 3,
    totalLessons: 20,
    learns: [
      "Connecter le travail quotidien aux objectifs stratégiques via l'approche projet",
      "Structurer l'effort de réalisation des KPI en projets d'optimisation pilotés",
      "Créer les conditions pour optimiser l'excellence projet dans votre organisation",
      "Appliquer la méthodologie de management de projet pour sortir du défaut de mise en œuvre",
      "Définir des initiatives stratégiques et les opérationnaliser avec méthode",
      "Développer la conscience projet pour accélérer la performance d'entreprise",
    ],
    chapters: [
      "Intro : Utiliser les projets pour atteindre les objectifs stratégiques",
      "Partie #1 : Structurer l'effort de réalisation des KPI en efforts de pilotage de projet d'optimisation",
      "Partie #2 : Créer les conditions pour optimiser l'excellence projet",
    ],
    benefits: [
      {
        title: "Huiler vos initiatives stratégiques",
        desc: "Définissez des initiatives stratégiques découlant de vrais enjeux et utilisez la méthodologie du management de projet pour les mettre en œuvre.",
      },
      {
        title: "Optimiser l'opérationnalisation",
        desc: "Grâce à la méthodologie du management de projet, traduisez vos initiatives stratégiques en termes opérationnels pour les mettre en œuvre plus aisément.",
      },
      {
        title: "Échapper au défaut d'exécution",
        desc: "Un plan d'entreprise vaut la peine quand les initiatives sont mises en œuvre. Découvrez comment la méthodologie du management de projet vous y aidera.",
      },
    ],
  },
  {
    slug: "management-strategique-du-capital-humain",
    title: "Management Stratégique du Capital Humain",
    category: "Parcours Dirigeant",
    price: 29000,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/management-strategique-du-capital-humain/",
    enrollUrl: "https://www.managersity.co/enroll/3248576",
    tagline: "Faites du capital humain un levier de performance stratégique : acquisition de talents, engagement, montée en compétences et rétention.",
    totalChapters: 4,
    totalLessons: 32,
    learns: [
      "Faire du capital humain un avantage compétitif durable",
      "Attirer, sélectionner et intégrer les meilleurs talents",
      "Structurer des plans de développement des compétences",
      "Piloter l'engagement et la rétention des collaborateurs",
      "Aligner la stratégie RH avec la vision d'entreprise",
      "Mesurer et optimiser la performance du capital humain",
    ],
    chapters: [
      "Introduction : Le capital humain, premier actif stratégique",
      "Partie #1 : Acquisition de talents et ingénierie de l'onboarding",
      "Partie #2 : Développement des compétences et montée en puissance",
      "Partie #3 : Engagement, fidélisation et pilotage de la performance",
    ],
    benefits: [
      {
        title: "Faire du capital humain un levier stratégique",
        desc: "Apprenez à transformer vos équipes en véritable avantage compétitif en alignant les talents sur les priorités de l'entreprise.",
      },
      {
        title: "Attirer et retenir les meilleurs profils",
        desc: "Disposez d'un système structuré d'acquisition, d'intégration et de fidélisation des talents qui propulse la performance collective.",
      },
      {
        title: "Piloter la montée en compétences",
        desc: "Construisez des plans de développement RH concrets qui accélèrent la progression de chaque talent vers l'excellence.",
      },
    ],
  },
  {
    slug: "modelisation-maitrise-financieres-pour-les-dirigeants",
    title: "Modélisation et Maîtrise Financière pour les Dirigeants",
    category: "Parcours Dirigeant",
    price: 29000,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/modelisation-maitrise-financieres-pour-les-dirigeants/",
    enrollUrl: "https://www.managersity.co/enroll/3248576",
    tagline: "Comment les chiffres sont faits, comment partir des objectifs stratégiques et des ambitions financières à la modélisation structurelle pour assurer la réalisation des performances attendues.",
    totalChapters: 2,
    totalLessons: 25,
    learns: [
      "Optimiser la maîtrise financière de votre organisation",
      "Scénariser la performance financière et créer les conditions factorielles de succès",
      "Apprendre à optimiser le P&L et partir de l'exploitation non satisfaisante aux chiffres attendus",
      "Comprendre les 6 insensibilités dangereuses des financiers et non-financiers",
      "Évaluer et optimiser la capacité financière d'une entreprise",
      "Contribuer à l'orchestration de la performance financière en tant que membre du CODIR",
    ],
    chapters: [
      "Intro : Seul le profit compte ?",
      "Partie #1 : L'art de faire les chiffres pour les dirigeants",
    ],
    benefits: [
      {
        title: "Démystifier la performance financière",
        desc: "Que vous soyez financier ou non, découvrez comment l'argent se fait et comment créer de la valeur dans une entreprise, étape par étape.",
      },
      {
        title: "Piloter et produire les chiffres",
        desc: "Vous n'attendrez plus le miracle des financiers. Vous aurez contribué à l'orchestration de la performance financière grâce à des méthodes éprouvées.",
      },
      {
        title: "De l'aisance méthodologique",
        desc: "Beaucoup pataugent quand il faut faire de la performance financière. Vous ferez désormais la différence grâce aux modèles et méthodes structurelles de ce module.",
      },
    ],
  },
  {
    slug: "gestion-des-parties-prenantes-networking-diplomatique-pour-les-dirigeants",
    title: "Gestion des Parties Prenantes & Networking Diplomatique pour les Dirigeants",
    category: "Parcours Dirigeant",
    price: 29900,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/gestion-des-parties-prenantes-networking-diplomatique-pour-les-dirigeants/",
    enrollUrl: "https://www.managersity.co/enroll/3249008",
    tagline: "Développez vos relations stratégiques et votre leadership diplomatique pour influencer vos parties prenantes et atteindre vos objectifs.",
    totalChapters: 5,
    totalLessons: 53,
    learns: [
      "Gérer vos parties prenantes (CA, actionnaires, CODIR, syndicats, clients, régulateur, État)",
      "Pratiquer un leadership politique sans naïveté dans les organisations complexes",
      "Bâtir et animer un réseau stratégique profitable et durable",
      "Maîtriser le lobbying et les relations institutionnelles",
      "Gérer les pressions et environnements professionnels difficiles",
      "Créer un cadre de relations qui fait que les autres veulent vous faire réussir",
    ],
    chapters: [
      "Intro : L'art de réussir en faisant réussir les autres",
      "Partie #1 : Réussir avec le Conseil d'Administration et les acteurs clés au groupe",
      "Partie #2 : Réussir avec son CODIR et faciliter les relations avec collaborateurs et partenaires sociaux",
      "Partie #3 : Réussir avec les autres partenaires à la performance (clients, fournisseurs, banquiers)",
      "Partie #4 : Networking, relations institutionnelles, agilité diplomatique & gestion des pressions",
    ],
    benefits: [
      {
        title: "Devenir un fin stratège relationnel",
        desc: "Prenez le contrôle de votre écosystème et créez un cadre de management et de développement efficace et profitable de vos relations.",
      },
      {
        title: "S'approprier les clés de la politique",
        desc: "Ne soyez plus victime des manigances politiques. Devenez un animal politique qui sait protéger et animer ses intérêts.",
      },
      {
        title: "Optimiser son réseau et ses relations",
        desc: "Utilisez des méthodes de networking et de lobbying pour développer votre réseau et animer vos relations de façon profitable et durable.",
      },
    ],
  },
  {
    slug: "lart-de-casser-la-baraque-pour-les-commerciaux",
    title: "L'Art de Casser la Baraque pour les Commerciaux",
    category: "Parcours Dirigeant",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/lart-de-casser-la-baraque-pour-les-commerciaux/",
    enrollUrl: "https://www.managersity.co/enroll/3253473",
    tagline: "Mindset, optimisation mentale et approche innovante pour intégrer la nouvelle psychologie de la vente et atteindre — et dépasser — vos objectifs commerciaux au quotidien.",
    totalChapters: 3,
    totalLessons: 18,
    learns: [
      "Doser son mindset pour devenir agressif, déterminé et avide de performance",
      "Structurer son approche marché avec organisation et discipline",
      "S'approprier la psychologie de la vente qui fait la différence",
      "Exercer les 5 droits du commercial que très peu exercent",
      "Développer la mentalité de gagnant et l'excellence vendeur 4.0",
      "Rester connecté à ses objectifs et attirer l'abondance commerciale",
    ],
    chapters: [
      "Intro : Êtes-vous vraiment un vendeur d'élite ?",
      "Partie #1 : Vendeur, maintenant cassez la baraque",
      "Partie #2 : Mentalité de gagnant et excellence vendeur 4.0 quotidienne",
    ],
    benefits: [
      {
        title: "Fluidifier l'obligation de faire les chiffres",
        desc: "Développez la simplicité et l'engagement mental requis pour capter et faire vos objectifs au quotidien tout en restant ZEN, DENSE & FOCUS.",
      },
      {
        title: "Massacrez la procrastination commerciale",
        desc: "Ne soyez plus un vendeur timide. Optimisez votre densité intérieure et la détermination opérationnelle pour faire vos quotas de vente à coup sûr.",
      },
      {
        title: "Attirer les opportunités et conclure plus facilement",
        desc: "Grâce à un FOCUS MENTAL et une densité dans l'engagement, vous aurez l'alignement nécessaire pour attirer les opportunités et conclure plus de deals.",
      },
    ],
  },
  {
    slug: "developper-son-potentiel-et-se-mettre-a-la-dimension-de-ses-reves",
    title: "Développer son Potentiel et se Mettre à la Dimension de ses Rêves",
    category: "Parcours Dirigeant",
    price: 11990,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/developper-son-potentiel-et-se-mettre-a-la-dimension-de-ses-reves/",
    enrollUrl: "https://www.managersity.co/enroll/3253630",
    tagline: "Prendre en main sa vie et sa carrière, prendre conscience de son potentiel et élaborer un plan de développement personnel pour réaliser la meilleure version de soi-même.",
    totalChapters: 5,
    totalLessons: 45,
    learns: [
      "Reprendre le contrôle de sa vie et de sa carrière",
      "S'approprier son potentiel et quitter la ligue des gens qui doutent d'eux-mêmes",
      "Piloter votre développement avec un plan structuré",
      "Refuser de se vendre moins cher et développer son engagement total",
      "Élaborer et réaliser son plan de développement personnel",
      "Transformer ses ambitions en réalité grâce à des méthodes éprouvées",
    ],
    chapters: [
      "Intro : Quel type de vie voulez-vous mener ?",
      "Partie #1 : L'art de prendre en charge le développement de son potentiel",
      "Partie #2 : L'art de développer son potentiel & devenir vraiment unique",
      "Partie #3 : L'art de densifier son engagement total pour le succès",
      "Partie #4 : Élaborer et réaliser son plan de développement personnel",
    ],
    benefits: [
      {
        title: "Reprendre le pouvoir sur sa vie",
        desc: "Décidez maintenant de ne plus faire dépendre des autres le magnifique potentiel que vous avez. Reprenez le pouvoir et prenez-vous en charge.",
      },
      {
        title: "Élaborer un plan de développement concret",
        desc: "Étudiez comment vous pensez, agissez et prenez-en le contrôle afin d'orienter vos actions vers ce qui vous permettra de devenir la meilleure version de vous-même.",
      },
      {
        title: "Transformer vos ambitions en réalité",
        desc: "Quel que soit le domaine de votre vie, ce module vous donne l'état d'esprit, la méthodologie et les outils pour transformer vos ambitions en réalité.",
      },
    ],
  },

  // ── MODULES CERTIFIANTS ───────────────────────────────────────────────────

  {
    slug: "le-game-de-la-strategie-disruption-marche",
    title: "Le Game de la Stratégie & Disruption Marché",
    category: "Modules Certifiants",
    price: 57000,
    originalPrice: 97000,
    shopUrl: "https://shop.managersity.com/produit/le-game-de-la-strategie-disruption-marche/",
    enrollUrl: "https://www.managersity.co/enroll/3386353",
    tagline: "Tout ce que vous avez besoin de savoir pour affiner votre profondeur stratégique, multiplier vos coups d'avance et disrupter vos marchés !",
    totalChapters: 3,
    totalLessons: 30,
    learns: [
      "Prendre le contrôle du game de la stratégie et sortir de la naïveté",
      "Structurer votre excellence stratégique et atteindre la perspicacité structurelle",
      "Multiplier vos coups d'avance et renforcer votre excellence tactique",
      "Identifier les signes de passivité et d'inaptitude stratégiques",
      "Formuler une stratégie pertinente et la déployer avec agilité",
      "Disrupter vos marchés et obtenir l'aisance nécessaire pour gagner",
    ],
    chapters: [
      "Introduction : À la source de la stratégie",
      "Partie #1 : Jouer abondamment le jeu de la stratégie et le gagner",
      "Partie #2 : Formulation stratégique et pertinence structurelle pour gagner",
    ],
    benefits: [
      {
        title: "Devenez un fin stratège",
        desc: "Chaque situation est un champ stratégique. Sortez des baisses de garde qui font tomber les autres dans la myopie stratégique et agissez avec sérénité.",
      },
      {
        title: "Agilisez comme un maître de jeu d'échec",
        desc: "Maîtrisez le jeu, scénarisez vos avances, multipliez vos options, modélisez vos mouvements et surprenez vos adversaires à chaque fois.",
      },
      {
        title: "Renforcez votre focus stratégique",
        desc: "Menez avec préparation et agilité le jeu de la stratégie. Sachez sur quoi parier, quels seront vos recours et les next steps pour continuer de gagner.",
      },
    ],
  },
  {
    slug: "lart-de-catalyser-et-piloter-la-performance",
    title: "L'Art de Catalyser et Piloter la Performance",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://www.managersity.co/products/courses/lart-de-catalyser-et-piloter-la-performance",
    enrollUrl: "https://www.managersity.co/enroll/3459601",
    tagline: "Ce module vous donne les outils et méthodes pour scénariser, catalyser et orchestrer la performance au day-to-day.",
    totalChapters: 3,
    totalLessons: 21,
    learns: [
      "Créer les conditions et le dispositif de pilotage de la performance",
      "Animer le dispositif de pilotage pour catalyser la performance au quotidien",
      "Développer la conscience de la performance globale",
      "Optimiser le cadre d'accélération de la performance managériale",
      "Travailler sur les 2 leviers de l'excellence managériale à l'ère de l'IA",
      "Réaliser une grande ambition managériale avec la méthode et l'engagement requis",
    ],
    chapters: [
      "Introduction : De l'ambition managériale à l'optimisation du cadre d'accélération de la performance",
      "Partie #1 : Créer les conditions et le dispositif de pilotage de la performance",
      "Partie #2 : Animer le dispositif de pilotage afin de catalyser la performance",
    ],
    benefits: [
      {
        title: "Devenir un leader attractif",
        desc: "Réussir à donner envie aux gens de venir vers vous, de vous écouter, vous suivre et s'engager pour les objectifs communs, tout en se laissant guider par vous !",
      },
      {
        title: "Optimiser sa capacité d'influence",
        desc: "Faites le parcours nécessaire à l'optimisation de votre capacité à devenir pour chacun de vos interlocuteurs critiques, celui ou celle qu'ils veulent suivre.",
      },
      {
        title: "Asseoir votre autorité morale",
        desc: "Dopez votre capacité à motiver, à vous élever et à élever les autres, à devenir la référence afin que les gens se tournent vers vous et vous suivent.",
      },
    ],
  },

  {
    slug: "le-coaching-managerial-4-0",
    title: "Le Coaching Managérial 4.0",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/le-coaching-managerial-4-0/",
    enrollUrl: "https://www.managersity.co/enroll/3451712",
    tagline: "Devenez un manager-coach d'exception : techniques de coaching, feedbacks structurés et développement des talents pour une équipe haute performance.",
    totalChapters: 3,
    totalLessons: 33,
    learns: [
      "Maîtriser la méthodologie pour coacher efficacement ses collaborateurs",
      "Amener les collaborateurs à concevoir et exécuter les tâches correctement",
      "Éviter les 5 pièges de l'évidence managériale qui font échouer les managers",
      "Utiliser les 5 composantes d'une instruction facile à exécuter",
      "Appliquer la méthode du tailleur en action dans différents contextes pratiques",
      "Déployer la formule de performance optimisée pour démultiplier les leaders",
    ],
    chapters: [
      "Introduction : L'art d'amener les collaborateurs à le concevoir et le faire de la même façon que vous",
      "Partie #1 : Créer et renforcer les bases de sa capacité d'influence",
      "Partie #2 : Optimiser sa posture managériale",
    ],
    benefits: [
      {
        title: "Devenir un leader attractif",
        desc: "Réussir à donner envie aux gens de venir vers vous, de vous écouter, vous suivre et s'engager pour les objectifs communs, tout en se laissant guider par vous !",
      },
      {
        title: "Optimiser sa capacité d'influence",
        desc: "Faites le parcours nécessaire à l'optimisation de votre capacité à devenir pour chacun de vos interlocuteurs critiques, celui ou celle qu'ils veulent suivre.",
      },
      {
        title: "Asseoir votre autorité morale",
        desc: "Dopez votre capacité à motiver, à vous élever et à élever les autres, à devenir la référence afin que les gens se tournent vers vous et vous suivent.",
      },
    ],
  },
  {
    slug: "reussir-son-management-commercial",
    title: "Réussir son Management Commercial",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/reussir-son-management-commercial/",
    enrollUrl: "https://www.managersity.co/enroll/3303782",
    tagline: "Les méthodes et outils pour piloter une équipe commerciale performante, atteindre les quotas et créer une culture de l'excellence commerciale.",
    totalChapters: 3,
    totalLessons: 45,
    learns: [
      "Scénariser et modéliser la croissance commerciale selon vos enjeux sectoriels",
      "Structurer votre couverture marché et réussir le maillage territorial et digital",
      "Orchestrer et catalyser la performance commerciale en temps réel",
      "Mettre en place les outils et dispositifs de management commercial efficaces",
      "Gérer les 9 cycles du management commercial pour garantir la croissance",
      "Travailler en synergie avec les autres fonctions pour atteindre vos chiffres",
    ],
    chapters: [
      "Introduction : État d'esprit, réflexes et focus pour s'approprier son job de manager commercial",
      "Partie #1 : Stratégie guerrière et méthodes d'optimisation stratégiques pour faire les chiffres",
      "Partie #2 : Outils et dispositif de management commercial",
    ],
    benefits: [
      {
        title: "Scénariser et modéliser la croissance commerciale",
        desc: "En fonction de votre secteur, des priorités stratégiques et de vos enjeux, définir une stratégie pour faire cartonner vos équipes.",
      },
      {
        title: "Réussir le maillage territorial et digital",
        desc: "Sachez comment structurer votre couverture marché, le déploiement et l'animation optimale de vos réseaux commerciaux.",
      },
      {
        title: "Orchestrer et catalyser la performance commerciale",
        desc: "Devenir un maître d'orchestre du monitoring et de l'optimisation continue de la performance commerciale.",
      },
    ],
  },
  {
    slug: "reussir-avec-son-conseil-dadministration-et-son-groupe",
    title: "Réussir avec son Conseil d'Administration et son Groupe",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/reussir-avec-son-conseil-dadministration-et-son-groupe/",
    enrollUrl: "https://www.managersity.co/enroll/3380143",
    tagline: "Nouvel état d'esprit, conscience politique et méthodes optimisées pour comprendre la dynamique d'un conseil d'administration et en prendre le contrôle avec ZEN, PROACTIVITÉ et MÉTHODE.",
    totalChapters: 3,
    totalLessons: 17,
    learns: [
      "Comprendre la dynamique politique du conseil d'administration",
      "Structurer la prise en charge des attentes et intérêts des administrateurs",
      "Retrouver la sérénité lors de vos sessions de CA",
      "Identifier qui détient le rapport de force et répondre efficacement aux attentes",
      "Utiliser des méthodes de networking et de lobbying pour animer vos relations",
      "Maîtriser les 8 pressions inutiles que les dirigeants se mettent dans leurs rapports avec le CA",
    ],
    chapters: [
      "Introduction : Quand le conseil vous fait trembler pour rien",
      "Partie #1 : Réussir avec le Conseil d'Administration et les acteurs clés au groupe",
      "Partie #2 : Maîtriser et gérer efficacement le jeu politique au sein du Conseil d'Administration",
    ],
    benefits: [
      {
        title: "Comprenez l'écosystème d'un conseil",
        desc: "Comprenez les attentes, élaborez des stratégies adaptées et maîtrisez la dynamique en jeu pour montrer que vous êtes l'homme ou la femme de la situation.",
      },
      {
        title: "Rassurez par votre prestance",
        desc: "Soyez celui ou celle que les gens sont heureux d'aider et de faire réussir parce qu'il sait comment servir les intérêts des gens et manager les relations de façon profitable.",
      },
      {
        title: "De la finesse méthodologique",
        desc: "Pour réussir dans le monde des affaires, il faut de la finesse et de la stratégie. Ce module inédit vous apporte exactement cela.",
      },
    ],
  },
  {
    slug: "leadership-situationnel-intelligence-emotionnelle",
    title: "Leadership Situationnel & Intelligence Émotionnelle",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/leadership-situationnel-intelligence-emotionnelle/",
    enrollUrl: "https://www.managersity.co/enroll/3382352",
    tagline: "Comment les grands leaders savent aborder et analyser les situations complexes avec hauteur, intelligence émotionnelle et capacité de processing pour RESTER L'HOMME OU LA FEMME de la situation.",
    totalChapters: 3,
    totalLessons: 40,
    learns: [
      "Adopter une attitude supérieure face aux situations difficiles",
      "Tenir face aux tensions constantes et rester focus sur l'essentiel",
      "Arriver à traiter efficacement et opérer les bons choix",
      "Autodire vos choix et assumer pleinement les résultats",
      "Développer l'art de décider et agir sereinement pour créer de la performance",
      "Maîtriser des méthodes inédites d'intelligence émotionnelle",
    ],
    chapters: [
      "Intro : Le vrai test de leadership",
      "Partie #1 : Reprendre le contrôle du jeu",
      "Partie #2 : L'art du processing pour gérer les situations sans émotion",
    ],
    benefits: [
      {
        title: "Arrêtez de râler et de paniquer",
        desc: "Tout n'a pas besoin de réaction. Maîtrisez les méthodes pour rester FOCUS RÉSULTATS et faire les bons choix qui conduiront vos équipes à la performance.",
      },
      {
        title: "Restez maître de la situation",
        desc: "Quand vos équipes pensent que tout est foutu, démontrez par votre sérénité qu'ils peuvent constamment compter sur vous. Les gens vous regardent !",
      },
      {
        title: "Des méthodes d'IE comme vous n'en avez jamais vues",
        desc: "Un leader ne doit pas se montrer fragile. Il doit être le guide vers qui les gens peuvent regarder quand ils perdent le contrôle. Devenez ce type de leader.",
      },
    ],
  },
  {
    slug: "choix-complexes-mecanismes-decisionnels",
    title: "Choix Complexes & Mécanismes Décisionnels",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/choix-complexes-mecanismes-decisionnels/",
    enrollUrl: "https://www.managersity.co/enroll/3382354",
    tagline: "Modèles et mécanismes décisionnels pour savoir lire entre les lignes, identifier les signaux critiques, se poser les bonnes questions et utiliser les bons critères pour prendre des décisions complexes.",
    totalChapters: 3,
    totalLessons: 19,
    learns: [
      "Optimiser votre décisivité face aux choix rapides et complexes",
      "Définir des modèles décisionnels et se poser les bonnes questions",
      "Rester connecté à vos objectifs sous pression",
      "Sortir de la fragilité face aux choix complexes",
      "Formuler et structurer votre approche décisionnelle",
      "Tirer des leçons de vos choix pour affuter votre capacité décisionnelle",
    ],
    chapters: [
      "Introduction : Quand vous n'avez pas d'autres choix que de décider",
      "Partie #1 : Comment sortir de la fragilité face aux choix complexes",
      "Partie #2 : L'art d'optimiser ses mécanismes décisionnels et faciliter ses choix",
    ],
    benefits: [
      {
        title: "Décidez avec focus et sérénité",
        desc: "Soyez le leader qui sait rester maître de la situation. Opérez les bonnes analyses et assurez la constance de l'orientation résultats pour votre équipe.",
      },
      {
        title: "Optimisez vos mécanismes décisionnels",
        desc: "Apprenez à identifier, dans chaque situation, la seule question qui compte vraiment. Délestez-vous de la pression liée au flot d'informations et faites le choix le plus judicieux.",
      },
      {
        title: "Renforcer votre agilité décisionnelle",
        desc: "Tout n'a pas besoin de réaction. Maîtrisez les méthodes pour rester FOCUS RÉSULTATS et lâchez prise pour opérer les choix qui permettront à votre équipe d'avancer.",
      },
    ],
  },
  {
    slug: "leadership-pouvoir-de-linfluence",
    title: "Leadership & Le Pouvoir de l'Influence au 21è Siècle",
    category: "Modules Certifiants",
    price: 34900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/leadership-pouvoir-de-linfluence/",
    enrollUrl: "https://www.managersity.co/enroll/3382352",
    tagline: "Développez un leadership authentique et maîtrisez l'art d'influencer sans autorité formelle pour mobiliser vos équipes et partenaires.",
    totalChapters: 3,
    totalLessons: 24,
    learns: [
      "Comprendre les mécanismes du pouvoir et de l'influence",
      "Développer un leadership authentique et inspirant",
      "Influencer sans autorité formelle ni contrainte",
      "Mobiliser et fédérer des équipes autour d'une vision",
      "Construire sa crédibilité et son capital relationnel",
      "Adopter les postures du leader d'influence à fort impact",
    ],
    chapters: [
      "Introduction : Leadership et influence — les fondements du pouvoir réel",
      "Partie #1 : Développer son leadership authentique et son capital d'influence",
      "Partie #2 : Techniques d'influence et mobilisation des acteurs clés",
    ],
    benefits: [
      {
        title: "Un leadership qui inspire et mobilise",
        desc: "Devenez un leader dont l'influence naturelle pousse les équipes à se dépasser et à s'engager pleinement dans les objectifs communs.",
      },
      {
        title: "Influencer sans autorité formelle",
        desc: "Maîtrisez les leviers de l'influence pour obtenir adhésion et coopération des équipes, pairs et partenaires sans avoir recours au pouvoir hiérarchique.",
      },
      {
        title: "Construire son capital relationnel",
        desc: "Développez la crédibilité, la confiance et les relations stratégiques qui font de vous un acteur incontournable dans votre organisation.",
      },
    ],
  },
  {
    slug: "structurer-et-piloter-une-vision-dentreprise",
    title: "Structurer et Piloter une Vision d'Entreprise",
    category: "Modules Certifiants",
    price: 27900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/structurer-et-piloter-une-vision-dentreprise/",
    enrollUrl: "https://www.managersity.co/enroll/3386353",
    tagline: "Définissez une vision ambitieuse, structurez-la en stratégie opérationnelle et mobilisez vos équipes autour d'un cap commun clair.",
    totalChapters: 3,
    totalLessons: 22,
    learns: [
      "Définir et formuler une vision d'entreprise claire et ambitieuse",
      "Traduire la vision en orientations stratégiques actionnables",
      "Créer l'alignement organisationnel autour d'un cap commun",
      "Piloter l'exécution de la vision et adapter la trajectoire",
      "Communiquer la vision pour embarquer les équipes",
      "Mesurer les indicateurs de cap et de progression stratégique",
    ],
    chapters: [
      "Introduction : Pourquoi la vision est l'ADN du leadership stratégique",
      "Partie #1 : Structurer et formuler une vision d'entreprise puissante",
      "Partie #2 : Déployer, piloter et faire vivre la vision au quotidien",
    ],
    benefits: [
      {
        title: "Une vision qui donne le cap",
        desc: "Construisez une vision d'entreprise claire, inspirante et différenciante qui oriente toutes les décisions stratégiques et opérationnelles.",
      },
      {
        title: "L'alignement de toute l'organisation",
        desc: "Apprenez à décliner la vision en objectifs concrets et à créer l'alignement de toutes vos équipes autour d'une direction commune.",
      },
      {
        title: "Piloter l'exécution stratégique",
        desc: "Disposez d'outils et de méthodes pour monitorer l'avancement, détecter les écarts et ajuster le tir pour rester sur la trajectoire de la vision.",
      },
    ],
  },
  {
    slug: "lart-de-structurer-et-optimiser-un-processus",
    title: "L'Art de Structurer et Optimiser un Processus",
    category: "Modules Certifiants",
    price: 21900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/lart-de-structurer-et-optimiser-un-processus/",
    enrollUrl: "https://www.managersity.co/enroll/3375598",
    tagline: "Cartographiez, simplifiez et optimisez vos processus pour gagner en efficacité opérationnelle et éliminer les sources de perte de performance.",
    totalChapters: 3,
    totalLessons: 20,
    learns: [
      "Cartographier et documenter les processus existants",
      "Identifier les goulots d'étranglement et sources de perte",
      "Simplifier et rationaliser les flux de travail",
      "Concevoir des processus optimisés et robustes",
      "Mettre en place des indicateurs de performance de processus",
      "Piloter l'amélioration continue des processus",
    ],
    chapters: [
      "Introduction : Pourquoi l'optimisation des processus est un impératif de performance",
      "Partie #1 : Cartographie, analyse et diagnostic des processus actuels",
      "Partie #2 : Conception, optimisation et pilotage des nouveaux processus",
    ],
    benefits: [
      {
        title: "Des processus au service de la performance",
        desc: "Transformez des processus chaotiques en machines de performance en éliminant les frictions, doublons et pertes de temps qui plombent votre efficacité.",
      },
      {
        title: "Une cartographie claire de l'organisation",
        desc: "Disposez d'une vision structurée de tous vos processus clés pour piloter l'organisation avec précision et prendre de meilleures décisions.",
      },
      {
        title: "Une culture d'amélioration continue",
        desc: "Installez une démarche d'amélioration continue qui pérennise les gains de performance et maintient l'organisation en état d'excellence opérationnelle.",
      },
    ],
  },
  {
    slug: "dispositif-outils-de-pilotage-commercial",
    title: "Dispositif & Outils de Pilotage Commercial",
    category: "Modules Certifiants",
    price: 21900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/dispositif-outils-de-pilotage-commercial/",
    enrollUrl: "https://www.managersity.co/enroll/3375598",
    tagline: "Plus de 50 outils, matrices, plans, feuilles de route et cadres pratiques pour modéliser, planifier, piloter et orchestrer plus aisément la performance commerciale.",
    totalChapters: 3,
    totalLessons: 20,
    learns: [
      "Structurer le cadre stratégique avec les meilleures matrices et cartes stratégiques",
      "Disposer d'une feuille de route — plan de développement sur 3 ans, plan trimestriel, feuille de route annuelle",
      "Piloter aisément avec des outils sur mesure d'animation commerciale",
      "Cartographier, planifier et orchestrer des dispositifs de performance commerciale",
      "Télécharger et adapter des templates à votre situation spécifique",
      "Maîtriser les outils modernes de scénarisation et de pilotage de la performance",
    ],
    chapters: [
      "Intro : L'art d'assurer l'orchestration et l'optimisation de la performance commerciale",
      "Partie #1 : Les outils de structuration et de planification de la performance commerciale",
      "Partie #2 : Les outils d'orchestration et de pilotage de la performance commerciale",
    ],
    benefits: [
      {
        title: "Finis les casses-têtes !",
        desc: "Découvrez plus de 50 outils pour cartographier, planifier et orchestrer des dispositifs de performance commerciale. Tout est mis à votre disposition.",
      },
      {
        title: "Des modèles d'outils expliqués en vidéo",
        desc: "Suivez pas à pas comment s'approprier chaque outil avec des travaux pratiques en vidéos. Téléchargez les templates et adaptez-les à votre situation.",
      },
      {
        title: "Émerveillez votre audience commerciale",
        desc: "Prenez le contrôle de votre pilotage commercial. Sachez minutieusement ce que vous devez faire chaque semaine pour atteindre vos objectifs.",
      },
    ],
  },
  {
    slug: "reussir-le-job-de-manager-commercial",
    title: "Réussir le Job de Manager Commercial",
    category: "Modules Certifiants",
    price: 21900,
    originalPrice: 34900,
    shopUrl: "https://shop.managersity.com/produit/reussir-le-job-de-manager-commercial/",
    enrollUrl: "https://www.managersity.co/enroll/3375573",
    tagline: "Développez un véritable état d'esprit marketing et adoptez les rôles, engagements et réflexes d'un manager commercial audacieux pour occuper le terrain et atteindre vos objectifs.",
    totalChapters: 3,
    totalLessons: 26,
    learns: [
      "Optimiser sa stratégie commerciale selon les priorités et enjeux sectoriels",
      "Réussir le maillage commercial — couverture marché, déploiement et animation des réseaux",
      "Orchestrer la performance et devenir un maître d'orchestre du monitoring commercial",
      "Jouer les 4 rôles clés du manager commercial au quotidien",
      "Mettre en mouvement vos équipes et réseaux commerciaux",
      "Maîtriser plus de 23 outils de scénarisation et de pilotage de la performance commerciale",
    ],
    chapters: [
      "Introduction : État d'esprit, réflexes et focus pour s'approprier son job de manager commercial",
      "Partie 1 : L'art de dynamiser son emprise managériale pour réussir son job de manager commercial",
      "Partie #2 : Stratégie guerrière et méthodes d'optimisation stratégiques pour faire les chiffres",
    ],
    benefits: [
      {
        title: "Huiler votre management commercial",
        desc: "Découvrez les nouveaux rôles critiques et la dimension stratégique, structurelle et opérationnelle requise pour mettre vos équipes en mouvement et atteindre vos objectifs.",
      },
      {
        title: "Créer les conditions de la performance commerciale",
        desc: "Découvrez les conditions et facteurs clés à activer ainsi que les mécanismes à déployer pour que vos commerciaux aient la fluidité nécessaire pour faire vos chiffres.",
      },
      {
        title: "Devenez un management commercial 4.0",
        desc: "Occupez le terrain, protégez votre part de marché et continuez à atteindre et dépasser vos objectifs commerciaux avec un état d'esprit et des outils modernes.",
      },
    ],
  },
  {
    slug: "batir-une-equipe-performante",
    title: "Bâtir une Équipe Performante",
    category: "Modules Certifiants",
    price: 19900,
    originalPrice: 59900,
    shopUrl: "https://shop.managersity.com/produit/batir-une-equipe-performante/",
    enrollUrl: "https://www.managersity.co/enroll/3418989",
    tagline: "Recrutez, onboardez, motivez et fidélisez les talents pour construire une équipe de haute performance et une culture de résultats.",
    totalChapters: 3,
    totalLessons: 33,
    learns: [
      "Structurer la construction d'une équipe solide, complémentaire et performante",
      "Attirer et intégrer les bons profils dans votre équipe",
      "Créer l'alchimie fonctionnelle pour développer la cohésion collective",
      "Appliquer la méthode des 4R pour éviter les pièges courants du management",
      "Construire une feuille de route pour modéler progressivement votre équipe",
      "Solidifier et généraliser l'excellence au sein de votre équipe",
    ],
    chapters: [
      "Intro : À quel point voulez-vous une équipe qui performe et vous permette de ne plus être un manager esclave ?",
      "Partie #1 : Les clés pour composer et constituer une équipe performante",
      "Partie #2 : Exceller dans le projet de bâtir une équipe performante",
    ],
    benefits: [
      {
        title: "Structurer la construction de son équipe",
        desc: "Créer une feuille de route pour affiner et optimiser le modèle de composition de son équipe.",
      },
      {
        title: "Optimiser l'alchimie fonctionnelle de son équipe",
        desc: "Définir le profil et optimiser la composition et le fonctionnement de son équipe pour maximiser la cohésion et la performance.",
      },
      {
        title: "Solidifier et généraliser l'excellence",
        desc: "Dopez votre capacité à motiver, à vous élever et à élever les autres pour que l'excellence devienne la norme dans votre équipe.",
      },
    ],
  },
  {
    slug: "management-du-changement-organisationnel",
    title: "Management du Changement Organisationnel",
    category: "Modules Certifiants",
    price: 19900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/management-du-changement-organisationnel/",
    enrollUrl: "https://www.managersity.co/enroll/3373559",
    tagline: "Pilotez la transformation de votre organisation en minimisant les résistances, en maximisant l'adoption et en préservant la performance.",
    totalChapters: 4,
    totalLessons: 39,
    learns: [
      "Identifier les contraintes culturelles et structurelles qui bloquent la performance",
      "Comprendre les 9 causes d'échec des projets de transformation d'entreprise",
      "Élaborer un plan de transformation et de mobilisation des équipes",
      "Modéliser la culture d'entreprise adéquate aux nouveaux enjeux",
      "Planifier, structurer et intégrer les changements organisationnels",
      "Maîtriser les 6 capacités transformatives clés pour une organisation performante",
    ],
    chapters: [
      "Intro : Lorsque votre organisation n'est pas calibrée pour vous permettre d'atteindre vos objectifs",
      "Partie #1 : Transformation culturelle et création de la culture de l'excellence",
      "Partie #2 : Planifier, structurer et intégrer les changements organisationnels",
      "Ressources gratuites",
    ],
    benefits: [
      {
        title: "Identifier les contraintes culturelles",
        desc: "Découvrez la méthodologie pour comprendre les contraintes culturelles et pratiques à l'excellence organisationnelle.",
      },
      {
        title: "Modéliser la culture d'entreprise adéquate",
        desc: "Découvrez comment créer la culture d'entreprise adaptée aux nouveaux enjeux et l'implémenter avec méthode.",
      },
      {
        title: "Structurer et intégrer efficacement les changements",
        desc: "Découvrez les outils pour instiguer et incruster les changements avec méthode et agilité dans votre organisation.",
      },
    ],
  },
  {
    slug: "methodes-de-gestion-du-temps-dorganisation-et-de-discipline-personnelle-pour-les-pros",
    title: "Méthodes de Gestion du Temps & de Discipline Personnelles pour les Pros",
    category: "Modules Certifiants",
    price: 19900,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/methodes-de-gestion-du-temps-dorganisation-et-de-discipline-personnelle-pour-les-pros/",
    enrollUrl: "https://www.managersity.co/enroll/3230856",
    tagline: "Des méthodes inédites de gestion du temps qui vous marcheront à coup sûr. Plus de 29 approches pour massacrer la procrastination et maîtriser votre organisation au quotidien.",
    totalChapters: 3,
    totalLessons: 51,
    learns: [
      "Optimiser son organisation et reprendre le contrôle de votre temps et de vos journées",
      "Améliorer le focus quotidien et se concentrer sur ses tâches clés",
      "Exceller et performer au quotidien en livrant vos quotas avec exemplarité",
      "Connecter ses journées à ses aspirations profondes",
      "Maîtriser les 10 ingrédients d'une journée fructueuse",
      "Anticiper sur les pressions et les gérer avec fluidité",
    ],
    chapters: [
      "Introduction : L'art de consacrer rigoureusement ses journées aux choses qui valent la peine",
      "Partie #1 : Conscience et méthodes de gestion optimisée du temps au quotidien",
      "Partie #2 : Gestion du stress — méthodes et organisation pour anticiper sur les pressions",
    ],
    benefits: [
      {
        title: "Atteignez la discipline personnelle",
        desc: "Avec ce module, vous n'allez plus être victime de la procrastination. 29 méthodes inédites vous permettront de faire ce que vous devez faire quand vous devez le faire.",
      },
      {
        title: "Massacrez la procrastination",
        desc: "Privez la procrastination de son emprise sur vous. Dopez votre énergie et votre agilité pour engager les actions que vous devez engager quand vous devez les engager.",
      },
      {
        title: "Maîtrisez votre organisation",
        desc: "Prenez le contrôle de votre vie et de votre carrière. Sachez minutieusement ce que vous devez faire chaque heure de vos journées pour atteindre vos objectifs.",
      },
    ],
  },
  {
    slug: "reussir-son-job-de-chef-de-service",
    title: "Réussir son Job de Chef de Service 5.0",
    category: "Management d'Équipe",
    price: 37000,
    originalPrice: 59000,
    shopUrl: "https://shop.managersity.com/produit/reussir-son-job-de-chef-de-service-5-0/",
    enrollUrl: "https://www.managersity.co/enroll/3724611",
    tagline: "Le mindset, les méthodes et l'organisation pour devenir le chef de service que votre N+1 n'a jamais besoin de relancer et que les autres départements respectent.",
    totalChapters: 7,
    totalLessons: 121,
    learns: [
      "Adopter la posture du chef de service contributeur qui sert l'organisation",
      "Comprendre et intégrer les priorités réelles de votre boss pour exceller au quotidien",
      "Devenir un délégataire leader qui anticipe, structure et délivre sans bruit",
      "Maîtriser les 5 qualités techniques pour ne jamais vous faire corriger",
      "Mettre en place un dispositif d'excellence opérationnelle : processus, KPI, amélioration continue",
      "Organiser votre journée pour piloter, décider, délivrer, développer et anticiper",
      "Déléguer efficacement et créer des checklists qui sécurisent vos enjeux même en votre absence",
      "Capaciter vos assistants pour en faire des relais fiables de votre performance",
      "Utiliser l'IA pour booster votre excellence opérationnelle",
    ],
    chapters: [
      "Partie 1 : Réussir son Job de Chef de Service",
      "Module 1 : Mindset du Chef de Service",
      "Module 2 : Le Chef de Service ou l'Expert/Ingénieur qui doit traiter les Sujets",
      "Module 3 : S'organiser pour Réussir en tant que Chef de Service",
      "Module 4 : Leadership & le Pouvoir de l'Influence au 21e Siècle",
      "Module 5 : Bâtir une Équipe Performante",
      "Module 6 : Management d'Équipe 4.0 & Création de la Dynamique Collective",
    ],
    benefits: [
      {
        title: "Devenir le chef de service que tout le monde respecte",
        desc: "Passez de \"super exécutant débordé\" à manager opérationnel qui délivre l'excellence. Votre N+1 pourra dormir tranquille sur votre périmètre.",
      },
      {
        title: "Un dispositif d'excellence opérationnelle",
        desc: "Structurez votre quotidien avec des dispositifs d'anticipation, des checklists et des rituels qui rendent la performance prévisible.",
      },
      {
        title: "Des assistants qui anticipent et délivrent",
        desc: "Capacitez vos assistants pour qu'ils absorbent votre charge, protègent vos priorités et deviennent des relais fiables de votre performance.",
      },
    ],
  },
  {
    slug: "parcours-chef-de-service-5-0",
    title: "Parcours Chef de Service 5.0",
    category: "Packs Phares",
    price: 97000,
    originalPrice: 129000,
    shopUrl: "https://shop.managersity.com/produit/parcours-chef-de-service/",
    enrollUrl: "https://www.managersity.co/enroll/3702379",
    tagline: "Le parcours complet pour passer d'expert nommé manager à chef de service que tout le monde respecte, qui délivre sans relance et dont l'équipe produit l'excellence opérationnelle.",
    totalChapters: 9,
    totalLessons: 169,
    learns: [
      "Maîtriser le job de chef de service de A à Z",
      "Adopter la bonne posture et les dispositifs d'organisation qui vous rendent fiable et contributif",
      "Affirmer votre autorité par la compétence et l'influence",
      "Bâtir une équipe solide et créer la dynamique collective de performance",
      "Coacher vos collaborateurs et les faire grandir",
      "Piloter la performance de votre équipe avec méthode et impact",
      "Déléguer avec intention et sécuriser vos enjeux même en votre absence",
      "Utiliser l'IA pour booster votre excellence opérationnelle",
    ],
    chapters: [
      "Partie 1 : Réussir son Job de Chef de Service",
      "Module 1 : Mindset du Chef de Service",
      "Module 2 : Le Chef de Service ou l'Expert/Ingénieur qui doit traiter les Sujets",
      "Module 3 : S'organiser pour Réussir en tant que Chef de Service",
      "Module 4 : Leadership & le Pouvoir de l'Influence au 21e Siècle",
      "Module 5 : Bâtir une Équipe Performante",
      "Module 6 : Management d'Équipe 4.0 & Création de la Dynamique Collective",
      "Module 7 : Coaching Managérial 4.0",
      "Module 8 : L'Art de Catalyser et Piloter la Performance",
    ],
    benefits: [
      {
        title: "La montée en compétences la plus complète",
        desc: "D'abord maîtriser le poste, ensuite développer le leadership — une progression pédagogique structurée pour une transformation complète.",
      },
      {
        title: "Un leadership qui mobilise",
        desc: "Le leadership au 21e siècle ne repose plus sur le titre. Il repose sur l'influence, la capacité à coacher et la dynamique que vous créez.",
      },
      {
        title: "Piloter la performance sans s'épuiser",
        desc: "Structurez, déléguez, anticipez et catalysez la performance au quotidien, avec des outils concrets et des cas réels par métier.",
      },
    ],
  },
  {
    slug: "optimiser-sa-posture-manageriale",
    title: "Optimiser sa Posture Managériale",
    category: "Modules Certifiants",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/optimiser-sa-posture-manageriale/",
    enrollUrl: "https://www.managersity.co/enroll/3386488",
    tagline: "Identifiez et corrigez les comportements qui limitent votre impact managérial pour adopter une posture de leadership optimal.",
    totalChapters: 3,
    totalLessons: 21,
    learns: [
      "Comprendre les règles d'excellence et d'élévation managériale",
      "Identifier les signes d'incompétence managériale et les corriger",
      "Développer la maturité managériale requise pour votre rôle et fonction",
      "Sortir de la naïveté pour adopter le bon état d'esprit et la bonne organisation",
      "S'auto-coacher en situation de tension pour garder le contrôle",
      "Élaborer un plan pour vous montrer à la dimension des enjeux managériaux",
    ],
    chapters: [
      "Introduction : Êtes-vous prêt pour le management ?",
      "Partie #1 : Développer la maturité managériale",
      "Partie #2 : Optimiser sa posture managériale",
    ],
    benefits: [
      {
        title: "Sortez de la naïveté managériale",
        desc: "Sachez ce qui fait la différence quand on est ou aspire à devenir manager et démonstrez-le au quotidien !",
      },
      {
        title: "Se montrer digne du rang",
        desc: "Montrez à travers votre maturité qu'on a bien fait de vous avoir confié le poste et méritez qu'on vous offre des next steps !",
      },
      {
        title: "Optimiser votre maturité managériale",
        desc: "Élaborez un plan pour opérer les transitions requises pour vous montrer à la dimension du rôle et de la fonction managériale.",
      },
    ],
  },
  {
    slug: "gestion-du-stress-et-des-pressions",
    title: "Gestion du Stress : Méthodes Inédites pour Anticiper les Pressions et les Gérer",
    category: "Modules Certifiants",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/gestion-du-stress-et-des-pressions/",
    enrollUrl: "https://www.managersity.co/enroll/3380144",
    tagline: "Méthodes inédites d'organisation et de gestion intelligente pour prévenir et gérer efficacement les moments de stress et rester en mesure de délivrer ses résultats en toute sérénité.",
    totalChapters: 3,
    totalLessons: 25,
    learns: [
      "Identifier vos sources de stress et prendre le contrôle de l'anticipation",
      "Décortiquer les mécanismes de déclenchement du stress",
      "Faciliter votre sérénité grâce à des méthodes inédites éprouvées avec des clients",
      "Anticiper sur les causes de stress pour en éliminer la majorité",
      "Garder la sérénité face aux pressions réelles qui font perdre la tête aux autres",
      "S'auto-coacher en situation de tension pour reprendre le contrôle",
    ],
    chapters: [
      "Introduction : Comment le stress est créé (inutilement)",
      "Partie #1 : Détecter les causes nuisibles de pression et les prévenir",
      "Partie #2 : Méthodes imparables pour éliminer ou gérer le stress au quotidien",
    ],
    benefits: [
      {
        title: "Anticiper sur les causes",
        desc: "La plupart de vos situations de stress peuvent être évitées si vous savez adopter l'état d'esprit et l'organisation nécessaires. Découvrez comment y arriver.",
      },
      {
        title: "Vous avez bien le contrôle",
        desc: "C'est vous qui laissez la négligence et le manque d'organisation rendre urgentes des situations qui auraient pu être anticipées. Reprenez le contrôle maintenant.",
      },
      {
        title: "Activez vos mécanismes de gestion sereine",
        desc: "Quand surviennent les pressions, gardez la sérénité et continuez de penser, décider et agir avec ordonnancement malgré les pressions réelles.",
      },
    ],
  },
  {
    slug: "piloter-sa-resilience-et-son-bien-etre-personnel",
    title: "Piloter sa Résilience et son Bien-Être Personnel",
    category: "Modules Certifiants",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/piloter-sa-resilience-et-son-bien-etre-personnel/",
    enrollUrl: "https://www.managersity.co/enroll/3422024",
    tagline: "État d'esprit, approches et mécanismes inédits pour trouver son épanouissement, piloter son bien-être au quotidien et rester fort et résilient dans un monde en tension.",
    totalChapters: 4,
    totalLessons: 68,
    learns: [
      "S'élever à la dimension des nouveaux enjeux professionnels du 21è siècle",
      "Orchestrer et manager son épanouissement et son bonheur quotidien",
      "Optimiser sa résilience personnelle et piloter son bien-être",
      "Transformer les obstacles en opportunités de croissance personnelle",
      "Mettre en place une feuille de route de gestion durable de son bien-être",
      "Maîtriser les mécanismes physiologiques du bien-être quotidien",
    ],
    chapters: [
      "Intro : En attendant que tout soit parfait — comment protéger son bien-être dans un monde en tension",
      "Partie #1 : Piloter son bien-être face aux nouvelles exigences professionnelles du 21è siècle",
      "Partie #2 : L'atelier du bien-être et du bonheur au quotidien pour les professionnels",
      "Partie #3 : De la fragilité au management de la résilience pour protéger son bien-être",
    ],
    benefits: [
      {
        title: "Manager votre bonheur au quotidien",
        desc: "Vous n'allez plus attendre pour être heureux. Ce cours propose un atelier spécial de management du bonheur avec des méthodes et outils pratiques pour calibrer votre bien-être.",
      },
      {
        title: "Reprenez le contrôle de votre épanouissement",
        desc: "Notre monde est en tension permanente. Mais tout dépend de votre posture, de votre état d'esprit et des mécanismes que vous déployez pour piloter votre bien-être.",
      },
      {
        title: "Optimiser les mécanismes de votre résilience",
        desc: "La plupart des gens attendent le bonheur. Ce module vous aide à piloter et calibrer votre résilience personnelle pour mieux faire face aux enjeux et rester heureux au quotidien.",
      },
    ],
  },

  // ── DÉVELOPPEMENT PERSONNEL ───────────────────────────────────────────────

  {
    slug: "intelligence-emotionnelle-gestion-des-relations-avec-les-autres",
    title: "Intelligence Émotionnelle & Gestion des Relations avec les Autres",
    category: "Développement Personnel",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/intelligence-emotionnelle-gestion-des-relations-avec-les-autres/",
    enrollUrl: "https://www.managersity.co/enroll/3234380",
    tagline: "Sortir de la fragilité émotionnelle, travailler son self-management, devenir confiant et autodéterminé, maîtriser ses émotions et retrouver la sérénité au quotidien.",
    totalChapters: 4,
    totalLessons: 48,
    learns: [
      "Savoir s'auto-manager et être maître de soi",
      "Sortir de la fragilité et augmenter sa confiance en soi",
      "Maîtriser ses émotions et le mécanisme de leur déclenchement",
      "Prendre en main sa vie et sa carrière et devenir le pilote de son destin",
      "Développer son intelligence émotionnelle au service du leadership",
      "Améliorer la qualité de toutes ses relations professionnelles et personnelles",
    ],
    chapters: [
      "Introduction : Arrivez-vous à vous manager ?",
      "Partie #1 : L'art de prendre en main sa vie et sa carrière",
      "Partie #2 : L'art de sortir de la fragilité émotionnelle & doper son intelligence émotionnelle",
      "Partie #3 : Leadership, communication efficace et gestion des malentendus",
    ],
    benefits: [
      {
        title: "Forgez votre caractère et votre self-management",
        desc: "Créez les conditions pour vous autodéterminer et développer votre capacité à gérer votre caractère et vos émotions, même sous pression.",
      },
      {
        title: "Soyez méthodique dans la gestion de vos émotions",
        desc: "Découvrez des méthodes inédites pour savoir désormais vous parler, vous auto-coacher et orienter vos réactions vers les attitudes qui vous soient profitables.",
      },
      {
        title: "Faites briller votre IE",
        desc: "Ne laissez plus les provocations, les attaques personnelles et les absurdités vous perturber. Prenez le contrôle de vos émotions et devenez imperturbable.",
      },
    ],
  },
  {
    slug: "lart-de-se-fixer-les-objectifs-les-atteindre-et-les-atteindre",
    title: "L'Art de se Fixer les Objectifs et les Atteindre",
    category: "Développement Personnel",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/lart-de-se-fixer-les-objectifs-les-atteindre-et-les-atteindre/",
    enrollUrl: "https://www.managersity.co/enroll/3230452",
    tagline: "Une méthodologie de management de vie et de carrière empruntée aux meilleurs dirigeants et athlètes pour transformer votre vie et votre carrière en chefs d'œuvre.",
    totalChapters: 3,
    totalLessons: 32,
    learns: [
      "Clarifier vos objectifs avec état d'esprit et méthodologie pour matérialiser vos rêves",
      "Structurer la planification sur 1, 5 et 25 ans avec la méthodologie requise",
      "Adopter l'organisation et la discipline requises pour atteindre vos objectifs",
      "Développer la clarté visionnaire pour votre vie et votre carrière",
      "S'aligner sur ses ambitions et les réaliser avec des méthodes de casseur de baraque",
      "Avoir une cartographie claire de pilotage dans chaque domaine important de votre vie",
    ],
    chapters: [
      "Introduction : L'audace de rêver et de se remettre en cause",
      "Partie #1 : L'art de s'aligner sur ses ambitions et les réaliser",
      "Partie #2 : Méthodes de casseur de baraque pour atteindre et dépasser ses objectifs",
    ],
    benefits: [
      {
        title: "Structurer la réalisation de vos objectifs",
        desc: "Découvrez l'état d'esprit et les méthodes utilisées par les plus grands succès pour se fixer des objectifs, les dépasser et réaliser des performances records.",
      },
      {
        title: "Ayez une cartographie claire de pilotage",
        desc: "Vous aurez désormais une carte pour ne plus naviguer à vue. Vous pourrez mieux utiliser vos ressources en sachant précisément à quoi les consacrer.",
      },
      {
        title: "Réussir, c'est atteindre ses objectifs",
        desc: "Quel que soit le domaine de votre vie où vous visez la réussite, ce module réunit l'état d'esprit, la méthodologie et les outils pour transformer vos ambitions en réalité.",
      },
    ],
  },
  {
    slug: "etat-desprit-resilience-entrepreneuriale",
    title: "État d'Esprit & Résilience Entrepreneuriale",
    category: "Développement Personnel",
    price: 14900,
    originalPrice: 39000,
    shopUrl: "https://shop.managersity.com/produit/etat-desprit-resilience-entrepreneuriale/",
    enrollUrl: "https://www.managersity.co/enroll/3253630",
    tagline: "Développez le mindset et la résilience d'un entrepreneur qui surmonte les obstacles, persévère et transforme les défis en opportunités de croissance.",
    totalChapters: 3,
    totalLessons: 20,
    learns: [
      "Développer l'état d'esprit de l'entrepreneur qui ne lâche pas",
      "Renforcer sa résilience face aux obstacles et aux échecs",
      "Transformer les défis en opportunités de croissance personnelle",
      "Prendre en main sa vie et son destin entrepreneurial",
      "Cultiver la persévérance et la densité intérieure requises pour réussir",
      "Piloter son orientation vers la performance et les résultats",
    ],
    chapters: [
      "Introduction : L'état d'esprit de l'entrepreneur résilient",
      "Partie #1 : Développer la résilience entrepreneuriale et sortir de la fragilité",
      "Partie #2 : Méthodes de casseur de baraque pour maintenir le cap vers ses objectifs",
    ],
    benefits: [
      {
        title: "Le mindset de l'entrepreneur qui réussit",
        desc: "Adoptez le même état d'esprit que les entrepreneurs qui transforment les obstacles en tremplins pour leur succès.",
      },
      {
        title: "Renforcer sa résilience personnelle",
        desc: "Développez la capacité à rebondir après chaque échec, à tirer les leçons et à avancer encore plus fort vers vos objectifs.",
      },
      {
        title: "Transformer les défis en opportunités",
        desc: "Apprenez à percevoir les problèmes non comme des obstacles mais comme des catalyseurs de croissance et de performance.",
      },
    ],
  },

  // ── TRANSFORMATION DIGITALE ───────────────────────────────────────────────

  {
    slug: "enjeux-business-methodologie-de-transformation-digitale",
    title: "Enjeux Business & Méthodologie de Transformation Digitale",
    category: "Transformation Digitale",
    price: 29900,
    originalPrice: 149000,
    shopUrl: "https://shop.managersity.com/produit/enjeux-business-methodologie-de-transformation-digitale/",
    enrollUrl: "https://www.managersity.co/enroll/3234082",
    tagline: "Embrassez l'aventure de la transformation digitale avec clarté, méthodes et aisance grâce à une méthodologie pour définir votre vision digitale et structurer votre déploiement.",
    totalChapters: 4,
    totalLessons: 33,
    learns: [
      "Comprendre l'univers digital et la transformation organisationnelle",
      "Modéliser l'intégration digitale et trouver votre schéma d'optimisation",
      "Structurer la maturation digitale et définir votre vision digitale",
      "Comment la technologie transforme les business models",
      "Éviter de tomber dans la paresse digitale et la passivité",
      "Élaborer une feuille de route de transformation digitale avec des outils pratiques",
    ],
    chapters: [
      "Intro : À quoi s'attendre lorsqu'on veut digitaliser ?",
      "Partie #1 : Dans l'univers technologique et digital — mindset & optimisation",
      "Partie #3 : Réduction du gap technologique et montée en régime digital",
      "Partie #4 : Étude de cas pratique — vision digitale et plan de transformation digitale",
    ],
    benefits: [
      {
        title: "Passez de spectateur à acteur",
        desc: "Entrez dans l'univers du digital et apprenez à en faire un levier pour vos enjeux de transformation. Utilisez le digital pour faire monter votre organisation en puissance.",
      },
      {
        title: "Obtenez votre certification en Transformation Digitale",
        desc: "Ayez votre mot à dire et challengez les propositions des experts. Contribuez efficacement à la montée en maturité digitale de votre organisation.",
      },
      {
        title: "Des outils pratiques à télécharger et utiliser",
        desc: "Vision digitale, évaluation de la maturité, feuille de route de transformation, culture digitale, data management — tout disponible avec des outils téléchargeables immédiatement.",
      },
    ],
  },
];
